import {
  Course,
  JobMatch,
  SkillPassportData,
  CertificateItem,
  AttendanceRecordItem,
  OfflineCourseItem,
  CareerRecommendation,
  CareerPlanStep,
} from '../types';

export const MOCK_TRAINEE = {
  id: 'trn-user-001',
  name: 'Ravindra Suresh Patil',
  email: 'ravindra.patil@coopsetu.in',
  role: 'Trainee',
  enrolled_institution: 'VAMNICOM Pune',
  programme: 'National Cooperative Management & Leadership Diploma',
  avatar_initials: 'RP',
  attendance_percentage: 88,
  skills_verified_count: 3,
  hours_completed: 34,
};

export const MOCK_COURSES: Course[] = [
  {
    id: 'crs-coop-mgmt',
    title: 'Cooperative Management Fundamentals',
    category: 'Management',
    level: 'Foundation',
    duration_hours: 40,
    instructor: 'Dr. Ramesh Kulkarni',
    rating: 4.8,
    enrolled: 1240,
    skills: ['Cooperative Management', 'Cooperative Governance'],
    progress: 75,
    modules: [
      {
        id: 'm1',
        title: '1. Introduction to Cooperative Principles & Values',
        duration: '18 min',
        completed: true,
        summary: 'Seven Rochdale principles and legal framework under MSCS Act.',
      },
      {
        id: 'm2',
        title: '2. Democratic Governance & Member Elections',
        duration: '24 min',
        completed: true,
        summary: 'General body meetings, board composition, and voter audit trails.',
      },
      {
        id: 'm3',
        title: '3. Financial Accounting in Cooperatives',
        duration: '32 min',
        completed: true,
        summary: 'P&L, balance sheets, statutory reserve funds, and dividend distribution.',
      },
      {
        id: 'm4',
        title: '4. Cooperative Byelaws & Regulatory Compliance',
        duration: '22 min',
        completed: false,
        summary: 'Statutory returns, ROC/RCS inspections, and audit compliance checklist.',
      },
      {
        id: 'm5',
        title: '5. Modernization & Digitization Roadmap',
        duration: '30 min',
        completed: false,
        summary: 'ERP integration, mobile banking for PACS, and traceability systems.',
      },
    ],
  },
  {
    id: 'crs-data-analytics',
    title: 'Data Analytics for Cooperatives',
    category: 'Technology',
    level: 'Intermediate',
    duration_hours: 48,
    instructor: 'Prof. Sunita Agarwal',
    rating: 4.6,
    enrolled: 640,
    skills: ['Data Analysis', 'Digital Tools'],
    progress: 20,
    modules: [
      {
        id: 'm201',
        title: '1. Fundamentals of Member Data & Ledger Analysis',
        duration: '25 min',
        completed: true,
        summary: 'Cleaning transaction logs and tracking member shareholdings.',
      },
      {
        id: 'm202',
        title: '2. Inventory & Procurement Forecasting',
        duration: '35 min',
        completed: false,
        summary: 'Predicting seasonal milk and agri procurement using trends.',
      },
    ],
  },
  {
    id: 'crs-rural-dev',
    title: 'Rural Development Fundamentals',
    category: 'Rural',
    level: 'Foundation',
    duration_hours: 32,
    instructor: 'Dr. Mohan Rao',
    rating: 4.7,
    enrolled: 820,
    skills: ['Rural Development'],
    progress: 0,
    modules: [
      {
        id: 'm301',
        title: '1. Socio-Economic Framework of Rural Cooperatives',
        duration: '20 min',
        completed: false,
        summary: 'Community needs assessment and SHG-Cooperative linkages.',
      },
    ],
  },
  {
    id: 'crs-dairy-ops',
    title: 'Dairy Cooperative Operations',
    category: 'Dairy',
    level: 'Intermediate',
    duration_hours: 60,
    instructor: 'Er. Vijay Patil',
    rating: 4.9,
    enrolled: 980,
    skills: ['Dairy Operations', 'Quality Assurance'],
    progress: 100,
    modules: [
      {
        id: 'm401',
        title: '1. Cold Chain Logistics & Chilling Plants',
        duration: '40 min',
        completed: true,
        summary: 'Bulk milk cooling units, temperature sensing, and logistics dispatch.',
      },
    ],
  },
];

export const MOCK_JOBS: JobMatch[] = [
  {
    id: 'job-dairy-supervisor-anand',
    title: 'Dairy Procurement Supervisor',
    employer: 'Amul Dairy Cooperative Union',
    location: 'Anand, Gujarat',
    sector: 'Dairy',
    type: 'Full-time',
    salary: '₹4,50,000 - ₹6,00,000',
    skills_required: ['Dairy Operations', 'Communication', 'Leadership'],
    openings: 5,
    posted_days_ago: 3,
    match_percentage: 92,
  },
  {
    id: 'job-cdo-ncdc',
    title: 'Cooperative Development Officer',
    employer: 'National Cooperative Development Corporation (NCDC)',
    location: 'New Delhi',
    sector: 'Cooperative Management',
    type: 'Full-time',
    salary: '₹5,50,000 - ₹7,00,000',
    skills_required: ['Cooperative Management', 'Rural Development', 'Data Analysis', 'Communication'],
    openings: 3,
    posted_days_ago: 7,
    match_percentage: 85,
  },
  {
    id: 'job-credit-officer-pune',
    title: 'Credit Officer - Cooperative Bank',
    employer: 'Maharashtra State Cooperative Bank',
    location: 'Pune, Maharashtra',
    sector: 'Banking',
    type: 'Full-time',
    salary: '₹3,80,000 - ₹5,20,000',
    skills_required: ['Credit Appraisal', 'Financial Management', 'Data Analysis'],
    openings: 8,
    posted_days_ago: 2,
    match_percentage: 78,
  },
  {
    id: 'job-agri-marketing-jaipur',
    title: 'Agri-Marketing Specialist',
    employer: 'Rajasthan Cooperative Marketing Federation',
    location: 'Jaipur, Rajasthan',
    sector: 'Agriculture',
    type: 'Full-time',
    salary: '₹3,50,000 - ₹4,80,000',
    skills_required: ['Digital Marketing', 'Communication', 'Rural Development'],
    openings: 4,
    posted_days_ago: 10,
    match_percentage: 64,
  },
];

export const MOCK_SKILL_PASSPORT: SkillPassportData = {
  skills: [
    {
      name: 'Cooperative Management',
      level: 'Proficient',
      confidence: 92,
      verified: true,
      category: 'Management',
      evidence: [
        { type: 'Course', title: 'Cooperative Management Fundamentals', date: '2026-08-15' },
        { type: 'Institutional Assessment', title: 'VAMNICOM Leadership Certification', date: '2026-09-02' },
      ],
    },
    {
      name: 'Communication & Facilitation',
      level: 'Proficient',
      confidence: 85,
      verified: true,
      category: 'Soft Skills',
      evidence: [
        { type: 'Assessment', title: 'Community Facilitation Skills Test', date: '2026-08-20' },
      ],
    },
    {
      name: 'Cooperative Governance',
      level: 'Intermediate',
      confidence: 78,
      verified: true,
      category: 'Management',
      evidence: [
        { type: 'Assessment', title: 'Governance & Byelaws Test', date: '2026-09-10' },
      ],
    },
    {
      name: 'Rural Development',
      level: 'Foundational',
      confidence: 60,
      verified: false,
      category: 'Domain',
      evidence: [
        { type: 'Course', title: 'Rural Development Basics', date: '2026-09-01' },
      ],
    },
    {
      name: 'Data Analysis',
      level: 'Foundational',
      confidence: 45,
      verified: false,
      category: 'Technical',
      evidence: [],
    },
  ],
  summary: {
    total_skills: 5,
    verified_count: 3,
    avg_confidence: 72,
  },
};

export const MOCK_CERTIFICATES: CertificateItem[] = [
  {
    id: 'CST-2026-DAI-00842',
    holder_name: 'Ravindra Suresh Patil',
    programme_title: 'Dairy Cooperative Operations',
    issuer: 'Institute of Rural Management, Anand (IRMA)',
    issue_date: '2026-07-15',
    expiry_date: '2029-07-15',
    status: 'Valid',
    grade: 'A',
    skills_certified: ['Dairy Operations', 'Cooperative Management', 'Quality Assurance'],
    verification_url: 'https://coopsetu.gov.in/verify/CST-2026-DAI-00842',
  },
  {
    id: 'CST-2026-MGT-00192',
    holder_name: 'Ravindra Suresh Patil',
    programme_title: 'Cooperative Governance & Legal Framework',
    issuer: 'National Council for Cooperative Training (NCCT)',
    issue_date: '2026-08-28',
    status: 'Valid',
    grade: 'A+',
    skills_certified: ['Cooperative Governance', 'Statutory Compliance'],
    verification_url: 'https://coopsetu.gov.in/verify/CST-2026-MGT-00192',
  },
];

export const MOCK_ATTENDANCE: AttendanceRecordItem[] = [
  {
    date: '2026-09-25',
    session: 'Cooperative Management Fundamentals - Batch B',
    status: 'present',
    method: 'QR Code Scan',
    timestamp: '09:42 AM',
  },
  {
    date: '2026-09-24',
    session: 'Financial Accounting in PACS - Workshop',
    status: 'present',
    method: 'QR Code Scan',
    timestamp: '09:38 AM',
  },
  {
    date: '2026-09-23',
    session: 'Data Analytics for Cooperatives - Lab',
    status: 'present',
    method: 'Biometric / QR',
    timestamp: '10:05 AM',
  },
  {
    date: '2026-09-22',
    session: 'Rural Banking & Credit Supervision',
    status: 'late',
    method: 'Manual Entry',
    timestamp: '10:25 AM',
  },
];

export const MOCK_OFFLINE_COURSES: OfflineCourseItem[] = [
  {
    id: 'crs-coop-mgmt',
    title: 'Cooperative Management Fundamentals',
    size_mb: 184,
    modules_count: 5,
    last_synced: 'Today, 08:30 AM',
    download_status: 'downloaded',
  },
  {
    id: 'crs-dairy-ops',
    title: 'Dairy Cooperative Operations',
    size_mb: 240,
    modules_count: 8,
    last_synced: 'Yesterday, 06:15 PM',
    download_status: 'downloaded',
  },
  {
    id: 'crs-data-analytics',
    title: 'Data Analytics for Cooperatives',
    size_mb: 120,
    modules_count: 4,
    last_synced: 'Pending download',
    download_status: 'pending',
  },
];

export const MOCK_CAREER_RECOMMENDATIONS: CareerRecommendation[] = [
  {
    priority: 1,
    type: 'course',
    title: 'Data Analytics for Cooperatives',
    reason: 'Fills biggest skill gap (Data Analysis missing for CDO role)',
    duration: '6 weeks',
    impact: '+15% match',
  },
  {
    priority: 2,
    type: 'course',
    title: 'Rural Development Fundamentals',
    reason: 'Required for CDO role at Intermediate level',
    duration: '4 weeks',
    impact: '+8% match',
  },
  {
    priority: 3,
    type: 'assessment',
    title: 'Cooperative Governance Assessment',
    reason: 'Verify your governance knowledge for cooperative employers',
    duration: '2 hours',
    impact: '+5% match',
  },
];

export const MOCK_CAREER_STEPS: CareerPlanStep[] = [
  { step: 1, title: 'Current: Diploma Trainee', status: 'current', timeline: 'Enrolled' },
  { step: 2, title: 'Junior Cooperative Officer', status: 'next', timeline: '3-6 months' },
  { step: 3, title: 'Cooperative Development Officer (CDO)', status: 'future', timeline: '12-18 months' },
  { step: 4, title: 'Senior CDO / Regional Programme Manager', status: 'future', timeline: '3-5 years' },
];
