export interface NCCTInstitution {
  id: string;
  name: string;
  shortCode: string;
  type: 'Apex' | 'RICM' | 'ICM';
  zone: 'West' | 'South' | 'North' | 'East' | 'Central' | 'North-East';
  city: string;
  state: string;
  directorName: string;
  phone: string;
  email: string;
  totalEnrolled: number;
  completionRate: number;
  placementRate: number;
  attendanceRate: number;
  activeProgrammes: number;
  activeBatches: number;
  certificatesIssued: number;
  hostelCapacity: number;
  hostelOccupancy: number;
  demographics: {
    gender: { female: number; male: number };
    category: { scSt: number; obc: number; general: number };
    ruralPercentage: number;
  };
  sectorDistribution: { sector: string; percentage: number; trainees: number }[];
  monthlyTrend: { month: string; enrolled: number; certified: number; placed: number }[];
}

export interface SkillDemandItem {
  id: string;
  skill: string;
  sector: string;
  demandCount: number;
  trainedCount: number;
  gapCount: number;
  trend: 'rising' | 'critical' | 'stable';
  trendLabel: string;
}

export const NATIONAL_APEX_METRICS = {
  totalTrainees: 48250,
  totalCertified: 39410,
  totalPlaced: 32800,
  activeEmployers: 1450,
  institutionsCount: 14,
  apexInstitute: 'VAMNICOM Pune',
  overallPlacementRate: 83.2,
  overallCompletionRate: 88.5,
  overallAttendanceRate: 94.8,
  funnel: [
    { stage: 'Trainees Enrolled', count: 48250, percentage: 100 },
    { stage: 'Course Completed', count: 42700, percentage: 88.5 },
    { stage: 'NCCT Certified', count: 39410, percentage: 81.7 },
    { stage: 'Applied for Cooperative Jobs', count: 36200, percentage: 75.0 },
    { stage: 'Employed in Cooperatives', count: 32800, percentage: 68.0 },
  ],
  sectorWorkforce: [
    { sector: 'PACS & Cooperative Banking', count: 15400, percentage: 32 },
    { sector: 'Dairy Cooperative Unions', count: 12500, percentage: 26 },
    { sector: 'Agriculture & Marketing (FPOs)', count: 7700, percentage: 16 },
    { sector: 'Cooperative Sugar Mills', count: 5300, percentage: 11 },
    { sector: 'Handloom & Handicrafts', count: 4350, percentage: 9 },
    { sector: 'Fisheries & Aquaculture', count: 3000, percentage: 6 },
  ],
  zones: [
    { zone: 'Western Zone (MH, GJ, GA)', trainees: 14200, percentage: 29 },
    { zone: 'Southern Zone (KA, TN, KL, AP, TS)', trainees: 12800, percentage: 27 },
    { zone: 'Northern Zone (PB, HR, UP, UK, RJ)', trainees: 11100, percentage: 23 },
    { zone: 'Eastern & Central (BR, WB, MP, OD)', trainees: 7350, percentage: 15 },
    { zone: 'North-East Zone (AS, ML, TR)', trainees: 2800, percentage: 6 },
  ],
};

export const NCCT_INSTITUTIONS: NCCTInstitution[] = [
  {
    id: 'vamnicom-pune',
    name: 'Vaikunth Mehta National Institute of Cooperative Management (VAMNICOM)',
    shortCode: 'VAMNICOM',
    type: 'Apex',
    zone: 'West',
    city: 'Pune',
    state: 'Maharashtra',
    directorName: 'Dr. Hema Yadav',
    phone: '+91 20 25701000',
    email: 'director@vamnicom.gov.in',
    totalEnrolled: 2450,
    completionRate: 97.2,
    placementRate: 94.5,
    attendanceRate: 97.8,
    activeProgrammes: 24,
    activeBatches: 42,
    certificatesIssued: 2380,
    hostelCapacity: 350,
    hostelOccupancy: 315,
    demographics: {
      gender: { female: 46, male: 54 },
      category: { scSt: 26, obc: 38, general: 36 },
      ruralPercentage: 68,
    },
    sectorDistribution: [
      { sector: 'Cooperative Banking & PACS', percentage: 38, trainees: 931 },
      { sector: 'Dairy Processing & Marketing', percentage: 28, trainees: 686 },
      { sector: 'Agri-Business Management', percentage: 20, trainees: 490 },
      { sector: 'Sugar Cooperative Governance', percentage: 14, trainees: 343 },
    ],
    monthlyTrend: [
      { month: 'Apr', enrolled: 320, certified: 290, placed: 275 },
      { month: 'May', enrolled: 380, certified: 350, placed: 330 },
      { month: 'Jun', enrolled: 410, certified: 395, placed: 375 },
      { month: 'Jul', enrolled: 440, certified: 425, placed: 405 },
      { month: 'Aug', enrolled: 460, certified: 450, placed: 428 },
      { month: 'Sep', enrolled: 440, certified: 430, placed: 410 },
    ],
  },
  {
    id: 'ricm-anand',
    name: 'Regional Institute of Cooperative Management, Anand / Gandhinagar',
    shortCode: 'RICM Anand',
    type: 'RICM',
    zone: 'West',
    city: 'Anand / Gandhinagar',
    state: 'Gujarat',
    directorName: 'Shri A.K. Asthana',
    phone: '+91 2692 261400',
    email: 'ricm.anand@ncct.ac.in',
    totalEnrolled: 1840,
    completionRate: 95.8,
    placementRate: 92.1,
    attendanceRate: 96.5,
    activeProgrammes: 18,
    activeBatches: 32,
    certificatesIssued: 1760,
    hostelCapacity: 220,
    hostelOccupancy: 205,
    demographics: {
      gender: { female: 48, male: 52 },
      category: { scSt: 29, obc: 41, general: 30 },
      ruralPercentage: 78,
    },
    sectorDistribution: [
      { sector: 'Dairy Operations & Chilling', percentage: 46, trainees: 846 },
      { sector: 'PACS Computerization & ERP', percentage: 26, trainees: 478 },
      { sector: 'Agricultural Marketing & Oilseeds', percentage: 16, trainees: 294 },
      { sector: 'Cooperative Auditing', percentage: 12, trainees: 222 },
    ],
    monthlyTrend: [
      { month: 'Apr', enrolled: 250, certified: 235, placed: 215 },
      { month: 'May', enrolled: 280, certified: 270, placed: 250 },
      { month: 'Jun', enrolled: 310, certified: 295, placed: 270 },
      { month: 'Jul', enrolled: 330, certified: 315, placed: 290 },
      { month: 'Aug', enrolled: 345, certified: 330, placed: 310 },
      { month: 'Sep', enrolled: 325, certified: 315, placed: 295 },
    ],
  },
  {
    id: 'ricm-bengaluru',
    name: 'Regional Institute of Cooperative Management, Bengaluru',
    shortCode: 'RICM Bengaluru',
    type: 'RICM',
    zone: 'South',
    city: 'Bengaluru',
    state: 'Karnataka',
    directorName: 'Dr. C. Nirmala',
    phone: '+91 80 23445566',
    email: 'ricm.bengaluru@ncct.ac.in',
    totalEnrolled: 1620,
    completionRate: 94.4,
    placementRate: 89.8,
    attendanceRate: 95.2,
    activeProgrammes: 16,
    activeBatches: 28,
    certificatesIssued: 1530,
    hostelCapacity: 180,
    hostelOccupancy: 165,
    demographics: {
      gender: { female: 44, male: 56 },
      category: { scSt: 27, obc: 37, general: 36 },
      ruralPercentage: 72,
    },
    sectorDistribution: [
      { sector: 'Cooperative Banking & Credit', percentage: 34, trainees: 550 },
      { sector: 'Dairy Processing (KMF / Nandini)', percentage: 30, trainees: 486 },
      { sector: 'Coffee & Spices Cooperatives', percentage: 22, trainees: 356 },
      { sector: 'Handloom & Silk Weaving', percentage: 14, trainees: 228 },
    ],
    monthlyTrend: [
      { month: 'Apr', enrolled: 220, certified: 205, placed: 185 },
      { month: 'May', enrolled: 250, certified: 235, placed: 210 },
      { month: 'Jun', enrolled: 270, certified: 255, placed: 230 },
      { month: 'Jul', enrolled: 295, certified: 280, placed: 255 },
      { month: 'Aug', enrolled: 305, certified: 290, placed: 265 },
      { month: 'Sep', enrolled: 280, certified: 265, placed: 240 },
    ],
  },
  {
    id: 'ricm-chandigarh',
    name: 'Regional Institute of Cooperative Management, Chandigarh',
    shortCode: 'RICM Chandigarh',
    type: 'RICM',
    zone: 'North',
    city: 'Chandigarh',
    state: 'Punjab & Haryana',
    directorName: 'Shri R.K. Sharma',
    phone: '+91 172 2701234',
    email: 'ricm.chandigarh@ncct.ac.in',
    totalEnrolled: 1480,
    completionRate: 93.6,
    placementRate: 88.4,
    attendanceRate: 94.6,
    activeProgrammes: 15,
    activeBatches: 26,
    certificatesIssued: 1385,
    hostelCapacity: 160,
    hostelOccupancy: 145,
    demographics: {
      gender: { female: 38, male: 62 },
      category: { scSt: 32, obc: 35, general: 33 },
      ruralPercentage: 81,
    },
    sectorDistribution: [
      { sector: 'Agricultural Marketing Federations (Markfed)', percentage: 40, trainees: 592 },
      { sector: 'Dairy (Verka & Vita)', percentage: 32, trainees: 474 },
      { sector: 'PACS Computerization & Governance', percentage: 20, trainees: 296 },
      { sector: 'Cooperative Cold Storages', percentage: 8, trainees: 118 },
    ],
    monthlyTrend: [
      { month: 'Apr', enrolled: 200, certified: 185, placed: 165 },
      { month: 'May', enrolled: 230, certified: 215, placed: 190 },
      { month: 'Jun', enrolled: 250, certified: 235, placed: 210 },
      { month: 'Jul', enrolled: 270, certified: 255, placed: 225 },
      { month: 'Aug', enrolled: 275, certified: 260, placed: 235 },
      { month: 'Sep', enrolled: 255, certified: 240, placed: 215 },
    ],
  },
  {
    id: 'ricm-patna',
    name: 'Regional Institute of Cooperative Management, Patna',
    shortCode: 'RICM Patna',
    type: 'RICM',
    zone: 'East',
    city: 'Patna',
    state: 'Bihar',
    directorName: 'Dr. S.P. Sinha',
    phone: '+91 612 2288990',
    email: 'ricm.patna@ncct.ac.in',
    totalEnrolled: 1350,
    completionRate: 91.8,
    placementRate: 85.2,
    attendanceRate: 93.4,
    activeProgrammes: 14,
    activeBatches: 24,
    certificatesIssued: 1240,
    hostelCapacity: 150,
    hostelOccupancy: 135,
    demographics: {
      gender: { female: 39, male: 61 },
      category: { scSt: 34, obc: 44, general: 22 },
      ruralPercentage: 85,
    },
    sectorDistribution: [
      { sector: 'Primary Agriculture Credit Societies', percentage: 42, trainees: 567 },
      { sector: 'Dairy (Sudha Milk Union)', percentage: 34, trainees: 459 },
      { sector: 'Fisheries Cooperatives', percentage: 14, trainees: 189 },
      { sector: 'Jute & Handloom Clusters', percentage: 10, trainees: 135 },
    ],
    monthlyTrend: [
      { month: 'Apr', enrolled: 180, certified: 165, placed: 140 },
      { month: 'May', enrolled: 210, certified: 190, placed: 160 },
      { month: 'Jun', enrolled: 230, certified: 210, placed: 180 },
      { month: 'Jul', enrolled: 245, certified: 225, placed: 195 },
      { month: 'Aug', enrolled: 255, certified: 235, placed: 205 },
      { month: 'Sep', enrolled: 230, certified: 215, placed: 185 },
    ],
  },
  {
    id: 'ricm-kalyani',
    name: 'Regional Institute of Cooperative Management, Kalyani',
    shortCode: 'RICM Kalyani',
    type: 'RICM',
    zone: 'East',
    city: 'Kalyani',
    state: 'West Bengal',
    directorName: 'Dr. Debabrata Mitra',
    phone: '+91 33 25828282',
    email: 'ricm.kalyani@ncct.ac.in',
    totalEnrolled: 1280,
    completionRate: 92.5,
    placementRate: 86.4,
    attendanceRate: 94.1,
    activeProgrammes: 13,
    activeBatches: 22,
    certificatesIssued: 1185,
    hostelCapacity: 140,
    hostelOccupancy: 120,
    demographics: {
      gender: { female: 42, male: 58 },
      category: { scSt: 33, obc: 32, general: 35 },
      ruralPercentage: 80,
    },
    sectorDistribution: [
      { sector: 'Fisheries & Prawn Culture', percentage: 36, trainees: 461 },
      { sector: 'Tea Cooperatives & Processing', percentage: 28, trainees: 358 },
      { sector: 'PACS Modernization', percentage: 22, trainees: 282 },
      { sector: 'Handloom & Tant Weavers', percentage: 14, trainees: 179 },
    ],
    monthlyTrend: [
      { month: 'Apr', enrolled: 170, certified: 155, placed: 135 },
      { month: 'May', enrolled: 195, certified: 180, placed: 155 },
      { month: 'Jun', enrolled: 220, certified: 200, placed: 175 },
      { month: 'Jul', enrolled: 235, certified: 220, placed: 190 },
      { month: 'Aug', enrolled: 240, certified: 225, placed: 195 },
      { month: 'Sep', enrolled: 220, certified: 205, placed: 180 },
    ],
  },
  {
    id: 'icm-madurai',
    name: 'Institute of Cooperative Management, Madurai',
    shortCode: 'ICM Madurai',
    type: 'ICM',
    zone: 'South',
    city: 'Madurai',
    state: 'Tamil Nadu',
    directorName: 'Dr. M. Ravichandran',
    phone: '+91 452 2458000',
    email: 'icm.madurai@ncct.ac.in',
    totalEnrolled: 1420,
    completionRate: 96.1,
    placementRate: 91.5,
    attendanceRate: 97.0,
    activeProgrammes: 16,
    activeBatches: 26,
    certificatesIssued: 1365,
    hostelCapacity: 160,
    hostelOccupancy: 150,
    demographics: {
      gender: { female: 52, male: 48 },
      category: { scSt: 28, obc: 46, general: 26 },
      ruralPercentage: 74,
    },
    sectorDistribution: [
      { sector: 'Handloom Weaving & Co-optex', percentage: 38, trainees: 540 },
      { sector: 'Dairy Processing (Aavin)', percentage: 32, trainees: 454 },
      { sector: 'Agricultural Credit & Banking', percentage: 20, trainees: 284 },
      { sector: 'FPO Management & Export', percentage: 10, trainees: 142 },
    ],
    monthlyTrend: [
      { month: 'Apr', enrolled: 190, certified: 180, placed: 165 },
      { month: 'May', enrolled: 220, certified: 210, placed: 195 },
      { month: 'Jun', enrolled: 240, certified: 230, placed: 210 },
      { month: 'Jul', enrolled: 260, certified: 250, placed: 230 },
      { month: 'Aug', enrolled: 270, certified: 260, placed: 240 },
      { month: 'Sep', enrolled: 240, certified: 235, placed: 215 },
    ],
  },
  {
    id: 'icm-dehradun',
    name: 'Institute of Cooperative Management, Dehradun',
    shortCode: 'ICM Dehradun',
    type: 'ICM',
    zone: 'North',
    city: 'Dehradun',
    state: 'Uttarakhand',
    directorName: 'Dr. Alok Verma',
    phone: '+91 135 2773344',
    email: 'icm.dehradun@ncct.ac.in',
    totalEnrolled: 980,
    completionRate: 92.0,
    placementRate: 84.6,
    attendanceRate: 93.8,
    activeProgrammes: 11,
    activeBatches: 18,
    certificatesIssued: 902,
    hostelCapacity: 120,
    hostelOccupancy: 100,
    demographics: {
      gender: { female: 45, male: 55 },
      category: { scSt: 22, obc: 28, general: 50 },
      ruralPercentage: 76,
    },
    sectorDistribution: [
      { sector: 'Horticulture & Apple Marketing', percentage: 42, trainees: 412 },
      { sector: 'Herbal & Medicinal Cooperatives', percentage: 28, trainees: 274 },
      { sector: 'PACS Multi-purpose Services', percentage: 20, trainees: 196 },
      { sector: 'Dairy Processing (Anchal)', percentage: 10, trainees: 98 },
    ],
    monthlyTrend: [
      { month: 'Apr', enrolled: 130, certified: 120, placed: 100 },
      { month: 'May', enrolled: 150, certified: 140, placed: 120 },
      { month: 'Jun', enrolled: 170, certified: 160, placed: 135 },
      { month: 'Jul', enrolled: 185, certified: 170, placed: 145 },
      { month: 'Aug', enrolled: 190, certified: 175, placed: 150 },
      { month: 'Sep', enrolled: 155, certified: 145, placed: 125 },
    ],
  },
  {
    id: 'icm-hyderabad',
    name: 'Institute of Cooperative Management, Hyderabad',
    shortCode: 'ICM Hyderabad',
    type: 'ICM',
    zone: 'South',
    city: 'Hyderabad',
    state: 'Telangana & AP',
    directorName: 'Dr. K. Srinivas Rao',
    phone: '+91 40 24018899',
    email: 'icm.hyderabad@ncct.ac.in',
    totalEnrolled: 1310,
    completionRate: 94.8,
    placementRate: 88.6,
    attendanceRate: 95.5,
    activeProgrammes: 14,
    activeBatches: 24,
    certificatesIssued: 1242,
    hostelCapacity: 150,
    hostelOccupancy: 130,
    demographics: {
      gender: { female: 43, male: 57 },
      category: { scSt: 30, obc: 42, general: 28 },
      ruralPercentage: 70,
    },
    sectorDistribution: [
      { sector: 'PACS Computerization & Core Banking', percentage: 44, trainees: 576 },
      { sector: 'Dairy (Vijaya Milk Union)', percentage: 26, trainees: 341 },
      { sector: 'Poultry & Livestock Cooperatives', percentage: 18, trainees: 236 },
      { sector: 'Weavers Cooperatives (Pochampally)', percentage: 12, trainees: 157 },
    ],
    monthlyTrend: [
      { month: 'Apr', enrolled: 180, certified: 170, placed: 150 },
      { month: 'May', enrolled: 205, certified: 195, placed: 175 },
      { month: 'Jun', enrolled: 225, certified: 215, placed: 190 },
      { month: 'Jul', enrolled: 240, certified: 230, placed: 205 },
      { month: 'Aug', enrolled: 250, certified: 240, placed: 215 },
      { month: 'Sep', enrolled: 210, certified: 200, placed: 180 },
    ],
  },
  {
    id: 'icm-bhopal',
    name: 'Institute of Cooperative Management, Bhopal',
    shortCode: 'ICM Bhopal',
    type: 'ICM',
    zone: 'Central',
    city: 'Bhopal',
    state: 'Madhya Pradesh',
    directorName: 'Shri Manoj Tiwari',
    phone: '+91 755 2661200',
    email: 'icm.bhopal@ncct.ac.in',
    totalEnrolled: 1240,
    completionRate: 93.1,
    placementRate: 86.8,
    attendanceRate: 94.0,
    activeProgrammes: 13,
    activeBatches: 22,
    certificatesIssued: 1155,
    hostelCapacity: 140,
    hostelOccupancy: 125,
    demographics: {
      gender: { female: 37, male: 63 },
      category: { scSt: 40, obc: 36, general: 24 },
      ruralPercentage: 84,
    },
    sectorDistribution: [
      { sector: 'Soybean & Oilseed Federations', percentage: 38, trainees: 471 },
      { sector: 'Primary Agriculture Credit', percentage: 32, trainees: 397 },
      { sector: 'Dairy Processing (Sanchi)', percentage: 20, trainees: 248 },
      { sector: 'Minor Forest Produce Cooperatives', percentage: 10, trainees: 124 },
    ],
    monthlyTrend: [
      { month: 'Apr', enrolled: 170, certified: 155, placed: 135 },
      { month: 'May', enrolled: 195, certified: 180, placed: 160 },
      { month: 'Jun', enrolled: 215, certified: 200, placed: 175 },
      { month: 'Jul', enrolled: 230, certified: 215, placed: 190 },
      { month: 'Aug', enrolled: 235, certified: 220, placed: 195 },
      { month: 'Sep', enrolled: 195, certified: 185, placed: 165 },
    ],
  },
  {
    id: 'icm-guwahati',
    name: 'Institute of Cooperative Management, Guwahati',
    shortCode: 'ICM Guwahati',
    type: 'ICM',
    zone: 'North-East',
    city: 'Guwahati',
    state: 'Assam & NE States',
    directorName: 'Dr. P.K. Hazarika',
    phone: '+91 361 2304400',
    email: 'icm.guwahati@ncct.ac.in',
    totalEnrolled: 1150,
    completionRate: 91.2,
    placementRate: 83.5,
    attendanceRate: 92.8,
    activeProgrammes: 12,
    activeBatches: 20,
    certificatesIssued: 1049,
    hostelCapacity: 130,
    hostelOccupancy: 115,
    demographics: {
      gender: { female: 54, male: 46 },
      category: { scSt: 48, obc: 24, general: 28 },
      ruralPercentage: 86,
    },
    sectorDistribution: [
      { sector: 'Tea Smallholders Cooperatives', percentage: 42, trainees: 483 },
      { sector: 'Handloom & Eri / Muga Silk', percentage: 30, trainees: 345 },
      { sector: 'Fisheries & Wetland Aquaculture', percentage: 16, trainees: 184 },
      { sector: 'Organic Spices & Citrus FPOs', percentage: 12, trainees: 138 },
    ],
    monthlyTrend: [
      { month: 'Apr', enrolled: 150, certified: 135, placed: 115 },
      { month: 'May', enrolled: 175, certified: 160, placed: 135 },
      { month: 'Jun', enrolled: 195, certified: 180, placed: 155 },
      { month: 'Jul', enrolled: 210, certified: 195, placed: 165 },
      { month: 'Aug', enrolled: 225, certified: 210, placed: 180 },
      { month: 'Sep', enrolled: 195, certified: 180, placed: 150 },
    ],
  },
  {
    id: 'icm-jaipur',
    name: 'Institute of Cooperative Management, Jaipur',
    shortCode: 'ICM Jaipur',
    type: 'ICM',
    zone: 'North',
    city: 'Jaipur',
    state: 'Rajasthan',
    directorName: 'Shri B.L. Meena',
    phone: '+91 141 2707788',
    email: 'icm.jaipur@ncct.ac.in',
    totalEnrolled: 1380,
    completionRate: 94.0,
    placementRate: 87.2,
    attendanceRate: 94.7,
    activeProgrammes: 14,
    activeBatches: 24,
    certificatesIssued: 1297,
    hostelCapacity: 150,
    hostelOccupancy: 138,
    demographics: {
      gender: { female: 36, male: 64 },
      category: { scSt: 36, obc: 42, general: 22 },
      ruralPercentage: 82,
    },
    sectorDistribution: [
      { sector: 'Cooperative Banking & PACS', percentage: 36, trainees: 497 },
      { sector: 'Dairy Processing (Saras)', percentage: 32, trainees: 442 },
      { sector: 'Agricultural Marketing (RAJFED)', percentage: 22, trainees: 304 },
      { sector: 'Wool & Handicrafts Weaving', percentage: 10, trainees: 138 },
    ],
    monthlyTrend: [
      { month: 'Apr', enrolled: 190, certified: 175, placed: 150 },
      { month: 'May', enrolled: 220, certified: 205, placed: 180 },
      { month: 'Jun', enrolled: 240, certified: 225, placed: 200 },
      { month: 'Jul', enrolled: 255, certified: 240, placed: 215 },
      { month: 'Aug', enrolled: 260, certified: 245, placed: 220 },
      { month: 'Sep', enrolled: 215, certified: 205, placed: 180 },
    ],
  },
  {
    id: 'icm-lucknow',
    name: 'Institute of Cooperative Management, Lucknow',
    shortCode: 'ICM Lucknow',
    type: 'ICM',
    zone: 'North',
    city: 'Lucknow',
    state: 'Uttar Pradesh',
    directorName: 'Dr. V.P. Singh',
    phone: '+91 522 2389900',
    email: 'icm.lucknow@ncct.ac.in',
    totalEnrolled: 1520,
    completionRate: 93.8,
    placementRate: 88.0,
    attendanceRate: 95.0,
    activeProgrammes: 15,
    activeBatches: 26,
    certificatesIssued: 1425,
    hostelCapacity: 170,
    hostelOccupancy: 155,
    demographics: {
      gender: { female: 40, male: 60 },
      category: { scSt: 31, obc: 45, general: 24 },
      ruralPercentage: 80,
    },
    sectorDistribution: [
      { sector: 'Cooperative Sugar Mills & Distilleries', percentage: 38, trainees: 578 },
      { sector: 'PACS Computerization & Governance', percentage: 32, trainees: 486 },
      { sector: 'Dairy Processing (Parag)', percentage: 20, trainees: 304 },
      { sector: 'Fertilizer & Seed Marketing (PCU)', percentage: 10, trainees: 152 },
    ],
    monthlyTrend: [
      { month: 'Apr', enrolled: 210, certified: 195, placed: 170 },
      { month: 'May', enrolled: 240, certified: 225, placed: 200 },
      { month: 'Jun', enrolled: 260, certified: 245, placed: 220 },
      { month: 'Jul', enrolled: 280, certified: 265, placed: 235 },
      { month: 'Aug', enrolled: 285, certified: 270, placed: 240 },
      { month: 'Sep', enrolled: 245, certified: 230, placed: 205 },
    ],
  },
  {
    id: 'icm-thiruvananthapuram',
    name: 'Institute of Cooperative Management, Thiruvananthapuram',
    shortCode: 'ICM Trivandrum',
    type: 'ICM',
    zone: 'South',
    city: 'Thiruvananthapuram',
    state: 'Kerala',
    directorName: 'Dr. G. Sasikumar',
    phone: '+91 471 2341200',
    email: 'icm.tvm@ncct.ac.in',
    totalEnrolled: 1390,
    completionRate: 97.0,
    placementRate: 93.4,
    attendanceRate: 97.4,
    activeProgrammes: 15,
    activeBatches: 24,
    certificatesIssued: 1348,
    hostelCapacity: 150,
    hostelOccupancy: 142,
    demographics: {
      gender: { female: 56, male: 44 },
      category: { scSt: 24, obc: 48, general: 28 },
      ruralPercentage: 66,
    },
    sectorDistribution: [
      { sector: 'Primary Agriculture Credit Societies (PACS)', percentage: 44, trainees: 612 },
      { sector: 'Dairy Processing (Milma)', percentage: 26, trainees: 361 },
      { sector: 'Consumer & Coir Cooperatives', percentage: 20, trainees: 278 },
      { sector: 'Fisheries (Matsyafed)', percentage: 10, trainees: 139 },
    ],
    monthlyTrend: [
      { month: 'Apr', enrolled: 190, certified: 185, placed: 170 },
      { month: 'May', enrolled: 220, certified: 215, placed: 200 },
      { month: 'Jun', enrolled: 240, certified: 235, placed: 220 },
      { month: 'Jul', enrolled: 255, certified: 248, placed: 235 },
      { month: 'Aug', enrolled: 265, certified: 258, placed: 245 },
      { month: 'Sep', enrolled: 220, certified: 212, placed: 200 },
    ],
  },
];

export const SKILL_DEMAND_INTELLIGENCE: SkillDemandItem[] = [
  {
    id: 'sd-01',
    skill: 'Dairy Operations & Cold Chain',
    sector: 'Dairy',
    demandCount: 5400,
    trainedCount: 3800,
    gapCount: 1600,
    trend: 'critical',
    trendLabel: 'Critical Gap (-1,600)',
  },
  {
    id: 'sd-02',
    skill: 'PACS Computerization & ERP Software',
    sector: 'Credit & Banking',
    demandCount: 6800,
    trainedCount: 5100,
    gapCount: 1700,
    trend: 'critical',
    trendLabel: 'Rising Demand (+38%)',
  },
  {
    id: 'sd-03',
    skill: 'Credit Appraisal & NPA Recovery',
    sector: 'Credit & Banking',
    demandCount: 4200,
    trainedCount: 3300,
    gapCount: 900,
    trend: 'rising',
    trendLabel: 'High Demand (+24%)',
  },
  {
    id: 'sd-04',
    skill: 'Cooperative Law & Statutory Audit',
    sector: 'Governance',
    demandCount: 2900,
    trainedCount: 2150,
    gapCount: 750,
    trend: 'rising',
    trendLabel: 'Specialized Demand',
  },
  {
    id: 'sd-05',
    skill: 'FPO Management & Value Addition',
    sector: 'Agriculture & Marketing',
    demandCount: 3600,
    trainedCount: 2800,
    gapCount: 800,
    trend: 'rising',
    trendLabel: 'Expanding Demand',
  },
  {
    id: 'sd-06',
    skill: 'Handloom Quality & Export Compliance',
    sector: 'Handloom',
    demandCount: 1800,
    trainedCount: 1450,
    gapCount: 350,
    trend: 'stable',
    trendLabel: 'Stable Demand',
  },
  {
    id: 'sd-07',
    skill: 'Fisheries Hatchery & Cold Storage',
    sector: 'Fisheries',
    demandCount: 1500,
    trainedCount: 1100,
    gapCount: 400,
    trend: 'rising',
    trendLabel: 'Emerging Sector',
  },
  {
    id: 'sd-08',
    skill: 'Cooperative Sugar Cogeneration Operations',
    sector: 'Sugar',
    demandCount: 1400,
    trainedCount: 1150,
    gapCount: 250,
    trend: 'stable',
    trendLabel: 'Seasonal Surge',
  },
];
