// =============================================================================
// Mock Application Seed Data — 12+ diverse demo applications across roles
// =============================================================================
import type { Application, Nomination, ExamRegistration, UpcomingEvent } from "@/types/application";

export const MOCK_APPLICATIONS: Application[] = [
  {
    id: "CSA-2026-00421",
    programmeId: "prog-coop-mgmt-001",
    programmeTitle: "Cooperative Management Fundamentals",
    programmeType: "training",
    institutionId: "inst-1",
    institutionName: "VAMNICOM Pune",
    traineeId: "trainee-ravindra",
    traineeName: "Ravindra Suresh Patil",
    traineeEmail: "ravindra.patil@coopsetu.ai",
    submittedAt: "2026-09-15T09:30:00Z",
    updatedAt: "2026-09-18T11:20:00Z",
    status: "trainer_approved",
    currentStage: "Institution Confirmation",
    eligibilityResult: "eligible",
    eligibilityDetails: [
      { label: "Minimum education satisfied", met: true },
      { label: "Cooperative membership verified", met: true },
      { label: "Age requirement (18+) satisfied", met: true },
    ],
    preferences: {
      preferredLanguage: "Marathi",
      preferredBatch: "Batch A — Morning",
      modePreference: "On-Campus",
      hostelRequired: true,
      mealRequired: true,
      transportRequired: false,
    },
    documents: [
      { type: "aadhaar", label: "Aadhaar Card", required: true, fileName: "aadhaar_ravindra.pdf", fileSize: 245000, uploadedAt: "2026-09-15T09:25:00Z", status: "verified" },
      { type: "education", label: "Education Certificate", required: true, fileName: "ssc_certificate.pdf", fileSize: 312000, uploadedAt: "2026-09-15T09:26:00Z", status: "verified" },
      { type: "membership", label: "Cooperative Membership Proof", required: true, fileName: "membership_card.jpg", fileSize: 128000, uploadedAt: "2026-09-15T09:27:00Z", status: "verified" },
      { type: "photo", label: "Passport Photo", required: true, fileName: "photo_ravindra.jpg", fileSize: 52000, uploadedAt: "2026-09-15T09:28:00Z", status: "verified" },
      { type: "employment", label: "Employment Proof", required: true, fileName: "employment_letter.pdf", fileSize: 198000, uploadedAt: "2026-09-15T09:29:00Z", status: "verified" },
    ],
    timeline: [
      { id: "tl-1", timestamp: "2026-09-15T09:30:00Z", actor: "Ravindra Suresh Patil", actorRole: "trainee", action: "Submitted application", status: "submitted" },
      { id: "tl-2", timestamp: "2026-09-15T10:00:00Z", actor: "System", actorRole: "system", action: "Eligibility check completed — Eligible", status: "pending_trainer" },
      { id: "tl-3", timestamp: "2026-09-18T11:20:00Z", actor: "Dr. Anand Deshmukh", actorRole: "trainer", action: "Reviewed application and approved", note: "Strong profile, appropriate for the programme. Recommended for Batch A.", status: "trainer_approved" },
    ],
    trainerNote: "Strong profile, appropriate for the programme. Recommended for Batch A.",
    personalInfo: {
      fullName: "Ravindra Suresh Patil",
      dateOfBirth: "1992-07-15",
      gender: "Male",
      phone: "+91 98765 43210",
      address: "Plot 12, Govind Nagar, Nashik 422 001",
      state: "Maharashtra",
      district: "Nashik",
      occupation: "PACS Secretary",
      cooperativeMembership: "Haveli Taluka PACS",
      education: "Graduate",
      experience: "4 years",
    },
  },
  {
    id: "CSA-2026-00389",
    programmeId: "prog-pacs-accounting-002",
    programmeTitle: "PACS Digital Accounting",
    programmeType: "training",
    institutionId: "inst-3",
    institutionName: "RICM Lucknow",
    traineeId: "trainee-ravindra",
    traineeName: "Ravindra Suresh Patil",
    traineeEmail: "ravindra.patil@coopsetu.ai",
    submittedAt: "2026-09-10T14:15:00Z",
    updatedAt: "2026-09-22T09:00:00Z",
    status: "batch_allocated",
    currentStage: "Batch Confirmed",
    eligibilityResult: "eligible",
    eligibilityDetails: [
      { label: "Minimum education satisfied", met: true },
      { label: "Cooperative membership verified", met: true },
      { label: "Age requirement satisfied", met: true },
    ],
    preferences: {
      preferredLanguage: "Hindi",
      preferredBatch: "Batch B — Evening",
      modePreference: "Hybrid",
      hostelRequired: false,
      mealRequired: false,
      transportRequired: false,
    },
    documents: [
      { type: "aadhaar", label: "Aadhaar Card", required: true, fileName: "aadhaar_ravindra.pdf", fileSize: 245000, uploadedAt: "2026-09-10T14:10:00Z", status: "verified" },
      { type: "education", label: "Education Certificate", required: true, fileName: "degree.pdf", fileSize: 450000, uploadedAt: "2026-09-10T14:11:00Z", status: "verified" },
      { type: "membership", label: "Cooperative Membership Proof", required: true, fileName: "membership.jpg", fileSize: 128000, uploadedAt: "2026-09-10T14:12:00Z", status: "verified" },
      { type: "photo", label: "Passport Photo", required: true, fileName: "photo.jpg", fileSize: 52000, uploadedAt: "2026-09-10T14:13:00Z", status: "verified" },
    ],
    timeline: [
      { id: "tl-1", timestamp: "2026-09-10T14:15:00Z", actor: "Ravindra Suresh Patil", actorRole: "trainee", action: "Submitted application", status: "submitted" },
      { id: "tl-2", timestamp: "2026-09-10T15:00:00Z", actor: "System", actorRole: "system", action: "Eligibility verified", status: "pending_trainer" },
      { id: "tl-3", timestamp: "2026-09-14T10:30:00Z", actor: "Dr. Meera Kulkarni", actorRole: "trainer", action: "Approved application", note: "Good academic background. Tally experience will be an asset.", status: "trainer_approved" },
      { id: "tl-4", timestamp: "2026-09-16T14:00:00Z", actor: "Dr. P. K. Swaminathan", actorRole: "institution", action: "Confirmed seat allocation", status: "institution_approved" },
      { id: "tl-5", timestamp: "2026-09-22T09:00:00Z", actor: "System", actorRole: "system", action: "Batch allocated: DCM-2026-04", status: "batch_allocated" },
    ],
    trainerNote: "Good academic background. Tally experience will be an asset.",
    batchAllocation: {
      batchId: "DCM-2026-04",
      batchName: "PACS Digital Accounting — Batch 04",
      trainerId: "trainer-2",
      trainerName: "Dr. Meera Kulkarni",
      room: "Room 204, Block B",
      startDate: "2026-11-10",
      endDate: "2026-12-05",
      time: "09:00 AM — 05:00 PM",
      mode: "Hybrid",
      hostelBlock: "Block A",
      hostelRoom: "Room 12",
      hostelBed: "Bed 03",
      seatNumber: 17,
    },
    personalInfo: {
      fullName: "Ravindra Suresh Patil",
      dateOfBirth: "1992-07-15",
      gender: "Male",
      phone: "+91 98765 43210",
      address: "Plot 12, Govind Nagar, Nashik 422 001",
      state: "Maharashtra",
      district: "Nashik",
      occupation: "PACS Secretary",
      cooperativeMembership: "Haveli Taluka PACS",
      education: "Graduate",
      experience: "4 years",
    },
  },
  {
    id: "CSA-2026-00358",
    programmeId: "prog-dairy-ops-003",
    programmeTitle: "Dairy Cooperative Operations",
    programmeType: "training",
    institutionId: "inst-1",
    institutionName: "VAMNICOM Pune",
    traineeId: "trainee-ravindra",
    traineeName: "Ravindra Suresh Patil",
    traineeEmail: "ravindra.patil@coopsetu.ai",
    submittedAt: "2026-09-05T11:00:00Z",
    updatedAt: "2026-09-12T15:45:00Z",
    status: "correction_required",
    currentStage: "Correction Required",
    eligibilityResult: "eligible",
    eligibilityDetails: [
      { label: "Minimum education satisfied", met: true },
      { label: "Cooperative membership verified", met: true },
      { label: "Age requirement satisfied", met: true },
    ],
    preferences: {
      preferredLanguage: "Marathi",
      preferredBatch: "Batch A",
      modePreference: "On-Campus",
      hostelRequired: true,
      mealRequired: true,
      transportRequired: true,
    },
    documents: [
      { type: "aadhaar", label: "Aadhaar Card", required: true, fileName: "aadhaar_ravindra.pdf", fileSize: 245000, uploadedAt: "2026-09-05T10:55:00Z", status: "verified" },
      { type: "education", label: "Education Certificate", required: true, fileName: "ssc_certificate.pdf", fileSize: 312000, uploadedAt: "2026-09-05T10:56:00Z", status: "verified" },
      { type: "membership", label: "Cooperative Membership Proof", required: true, fileName: "old_membership.jpg", fileSize: 45000, uploadedAt: "2026-09-05T10:57:00Z", status: "invalid", notes: "Membership card image is blurred and unreadable. Please upload a clear copy." },
      { type: "photo", label: "Passport Photo", required: true, fileName: "photo.jpg", fileSize: 52000, uploadedAt: "2026-09-05T10:58:00Z", status: "verified" },
      { type: "medical", label: "Medical Fitness Certificate", required: true, status: "pending" },
    ],
    timeline: [
      { id: "tl-1", timestamp: "2026-09-05T11:00:00Z", actor: "Ravindra Suresh Patil", actorRole: "trainee", action: "Submitted application", status: "submitted" },
      { id: "tl-2", timestamp: "2026-09-05T11:30:00Z", actor: "System", actorRole: "system", action: "Eligibility verified", status: "pending_trainer" },
      { id: "tl-3", timestamp: "2026-09-12T15:45:00Z", actor: "Dr. Anand Deshmukh", actorRole: "trainer", action: "Requested correction", note: "Cooperative membership proof is blurred and unreadable. Medical fitness certificate is missing. Please upload clear copies.", status: "correction_required" },
    ],
    correctionNote: "Cooperative membership proof is blurred and unreadable. Medical fitness certificate is missing. Please upload clear copies.",
    personalInfo: {
      fullName: "Ravindra Suresh Patil",
      dateOfBirth: "1992-07-15",
      gender: "Male",
      phone: "+91 98765 43210",
      address: "Plot 12, Govind Nagar, Nashik 422 001",
      state: "Maharashtra",
      district: "Nashik",
      occupation: "PACS Secretary",
      cooperativeMembership: "Haveli Taluka PACS",
      education: "Graduate",
      experience: "4 years",
    },
  },
  {
    id: "CSA-2026-00302",
    programmeId: "prog-coop-governance-004",
    programmeTitle: "Cooperative Governance & Audit",
    programmeType: "training",
    institutionId: "inst-4",
    institutionName: "ICM Bhopal",
    traineeId: "trainee-ravindra",
    traineeName: "Ravindra Suresh Patil",
    traineeEmail: "ravindra.patil@coopsetu.ai",
    submittedAt: "2026-08-20T09:00:00Z",
    updatedAt: "2026-08-28T16:00:00Z",
    status: "rejected",
    currentStage: "Rejected",
    eligibilityResult: "not_eligible",
    eligibilityDetails: [
      { label: "Minimum education satisfied", met: true },
      { label: "Cooperative membership verified", met: true },
      { label: "2+ years experience required", met: false, reason: "Applicant has stated 1 year experience. Programme requires minimum 2 years." },
    ],
    preferences: {
      preferredLanguage: "Hindi",
      preferredBatch: "Batch A",
      modePreference: "Hybrid",
      hostelRequired: false,
      mealRequired: false,
      transportRequired: false,
    },
    documents: [
      { type: "aadhaar", label: "Aadhaar Card", required: true, fileName: "aadhaar.pdf", fileSize: 245000, uploadedAt: "2026-08-20T08:55:00Z", status: "uploaded" },
      { type: "education", label: "Education Certificate", required: true, fileName: "degree.pdf", fileSize: 450000, uploadedAt: "2026-08-20T08:56:00Z", status: "uploaded" },
      { type: "experience", label: "Experience Proof", required: true, fileName: "experience_letter.pdf", fileSize: 156000, uploadedAt: "2026-08-20T08:57:00Z", status: "uploaded" },
    ],
    timeline: [
      { id: "tl-1", timestamp: "2026-08-20T09:00:00Z", actor: "Ravindra Suresh Patil", actorRole: "trainee", action: "Submitted application", status: "submitted" },
      { id: "tl-2", timestamp: "2026-08-20T09:30:00Z", actor: "System", actorRole: "system", action: "Eligibility check flagged", note: "Experience requirement not fully met", status: "pending_trainer" },
      { id: "tl-3", timestamp: "2026-08-28T16:00:00Z", actor: "Dr. Vikram Rao", actorRole: "trainer", action: "Rejected application", note: "The programme requires a minimum of 2 years of cooperative experience. Applicant has stated only 1 year. Please re-apply after gaining more experience.", status: "rejected" },
    ],
    rejectionReason: "The programme requires a minimum of 2 years of cooperative experience. Applicant has stated only 1 year. Please re-apply after gaining more experience.",
    personalInfo: {
      fullName: "Ravindra Suresh Patil",
      dateOfBirth: "1992-07-15",
      gender: "Male",
      phone: "+91 98765 43210",
      address: "Plot 12, Govind Nagar, Nashik 422 001",
      state: "Maharashtra",
      district: "Nashik",
      occupation: "PACS Secretary",
      cooperativeMembership: "Haveli Taluka PACS",
      education: "Graduate",
      experience: "1 year",
    },
  },
  {
    id: "CSA-2026-00455",
    programmeId: "prog-coop-finance-006",
    programmeTitle: "Cooperative Financial Management",
    programmeType: "training",
    institutionId: "inst-1",
    institutionName: "VAMNICOM Pune",
    traineeId: "trainee-ravindra",
    traineeName: "Ravindra Suresh Patil",
    traineeEmail: "ravindra.patil@coopsetu.ai",
    submittedAt: "2026-09-28T10:00:00Z",
    updatedAt: "2026-09-28T10:00:00Z",
    status: "pending_trainer",
    currentStage: "Pending Trainer Review",
    eligibilityResult: "eligible",
    eligibilityDetails: [
      { label: "Graduate qualification met", met: true },
      { label: "Cooperative employment verified", met: true },
      { label: "Age requirement satisfied", met: true },
    ],
    preferences: {
      preferredLanguage: "Marathi",
      preferredBatch: "Batch A — Morning",
      modePreference: "On-Campus",
      hostelRequired: true,
      mealRequired: true,
      transportRequired: false,
    },
    documents: [
      { type: "aadhaar", label: "Aadhaar Card", required: true, fileName: "aadhaar_ravindra.pdf", fileSize: 245000, uploadedAt: "2026-09-28T09:50:00Z", status: "uploaded" },
      { type: "education", label: "Education Certificate", required: true, fileName: "degree.pdf", fileSize: 450000, uploadedAt: "2026-09-28T09:52:00Z", status: "uploaded" },
      { type: "employment", label: "Employment Letter", required: true, fileName: "employment.pdf", fileSize: 198000, uploadedAt: "2026-09-28T09:54:00Z", status: "uploaded" },
      { type: "membership", label: "Cooperative Membership Proof", required: true, fileName: "membership.jpg", fileSize: 128000, uploadedAt: "2026-09-28T09:55:00Z", status: "uploaded" },
      { type: "photo", label: "Passport Photo", required: true, fileName: "photo.jpg", fileSize: 52000, uploadedAt: "2026-09-28T09:56:00Z", status: "uploaded" },
    ],
    timeline: [
      { id: "tl-1", timestamp: "2026-09-28T10:00:00Z", actor: "Ravindra Suresh Patil", actorRole: "trainee", action: "Submitted application", status: "submitted" },
      { id: "tl-2", timestamp: "2026-09-28T10:30:00Z", actor: "System", actorRole: "system", action: "Eligibility verified — Eligible", status: "pending_trainer" },
    ],
    personalInfo: {
      fullName: "Ravindra Suresh Patil",
      dateOfBirth: "1992-07-15",
      gender: "Male",
      phone: "+91 98765 43210",
      address: "Plot 12, Govind Nagar, Nashik 422 001",
      state: "Maharashtra",
      district: "Nashik",
      occupation: "PACS Secretary",
      cooperativeMembership: "Haveli Taluka PACS",
      education: "Graduate",
      experience: "4 years",
    },
  },
  {
    id: "CSA-2026-00278",
    programmeId: "prog-digital-lit-005",
    programmeTitle: "Digital Literacy for Rural Cooperatives",
    programmeType: "digital-literacy",
    institutionId: "inst-5",
    institutionName: "ICM Guwahati",
    traineeId: "trainee-ravindra",
    traineeName: "Ravindra Suresh Patil",
    traineeEmail: "ravindra.patil@coopsetu.ai",
    submittedAt: "2026-08-10T08:00:00Z",
    updatedAt: "2026-09-05T12:00:00Z",
    status: "completed",
    currentStage: "Completed",
    eligibilityResult: "eligible",
    eligibilityDetails: [
      { label: "Minimum education satisfied", met: true },
      { label: "Cooperative membership verified", met: true },
      { label: "Age requirement satisfied", met: true },
    ],
    preferences: {
      preferredLanguage: "Hindi",
      preferredBatch: "Batch A",
      modePreference: "On-Campus",
      hostelRequired: false,
      mealRequired: false,
      transportRequired: false,
    },
    documents: [
      { type: "aadhaar", label: "Aadhaar Card", required: true, fileName: "aadhaar.pdf", fileSize: 245000, uploadedAt: "2026-08-10T07:55:00Z", status: "verified" },
      { type: "membership", label: "Cooperative Membership Proof", required: true, fileName: "membership.jpg", fileSize: 128000, uploadedAt: "2026-08-10T07:56:00Z", status: "verified" },
      { type: "photo", label: "Passport Photo", required: true, fileName: "photo.jpg", fileSize: 52000, uploadedAt: "2026-08-10T07:57:00Z", status: "verified" },
    ],
    timeline: [
      { id: "tl-1", timestamp: "2026-08-10T08:00:00Z", actor: "Ravindra Suresh Patil", actorRole: "trainee", action: "Submitted application", status: "submitted" },
      { id: "tl-2", timestamp: "2026-08-10T08:30:00Z", actor: "System", actorRole: "system", action: "Eligibility verified", status: "pending_trainer" },
      { id: "tl-3", timestamp: "2026-08-12T10:00:00Z", actor: "Ms. Sunita Bhat", actorRole: "trainer", action: "Approved", status: "trainer_approved" },
      { id: "tl-4", timestamp: "2026-08-14T09:00:00Z", actor: "Dr. P. K. Swaminathan", actorRole: "institution", action: "Seat confirmed", status: "institution_approved" },
      { id: "tl-5", timestamp: "2026-08-15T10:00:00Z", actor: "System", actorRole: "system", action: "Batch allocated", status: "batch_allocated" },
      { id: "tl-6", timestamp: "2026-09-05T12:00:00Z", actor: "System", actorRole: "system", action: "Programme completed — Certificate issued", status: "completed" },
    ],
    personalInfo: {
      fullName: "Ravindra Suresh Patil",
      dateOfBirth: "1992-07-15",
      gender: "Male",
      phone: "+91 98765 43210",
      address: "Plot 12, Govind Nagar, Nashik 422 001",
      state: "Maharashtra",
      district: "Nashik",
      occupation: "PACS Secretary",
      cooperativeMembership: "Haveli Taluka PACS",
      education: "Graduate",
      experience: "4 years",
    },
  },
];

export const MOCK_NOMINATIONS: Nomination[] = [
  {
    id: "NOM-2026-00145",
    programmeId: "prog-coop-mgmt-001",
    programmeTitle: "Cooperative Management Fundamentals",
    institutionId: "inst-1",
    institutionName: "VAMNICOM Pune",
    traineeId: "trainee-ravindra",
    traineeName: "Ravindra Suresh Patil",
    cooperativeId: "coop-2",
    cooperativeName: "Haveli Taluka PACS",
    nominatedBy: "Kishan Rao Patil, President — Haveli Taluka PACS",
    submittedAt: "2026-09-20T10:00:00Z",
    updatedAt: "2026-09-25T14:00:00Z",
    status: "trainer_review",
    timeline: [
      { id: "n-tl-1", timestamp: "2026-09-20T10:00:00Z", actor: "Haveli Taluka PACS", actorRole: "institution", action: "Nomination submitted by cooperative", status: "submitted" },
      { id: "n-tl-2", timestamp: "2026-09-22T09:00:00Z", actor: "Cooperative Federation", actorRole: "institution", action: "Cooperative review completed — approved", status: "cooperative_review" },
      { id: "n-tl-3", timestamp: "2026-09-25T14:00:00Z", actor: "System", actorRole: "system", action: "Referred to trainer for review", status: "trainer_review" },
    ],
    notes: "Nominated as the primary representative of Haveli Taluka PACS for the Q4 2026 cohort.",
  },
  {
    id: "NOM-2026-00098",
    programmeId: "prog-pacs-accounting-002",
    programmeTitle: "PACS Digital Accounting",
    institutionId: "inst-3",
    institutionName: "RICM Lucknow",
    traineeId: "trainee-ravindra",
    traineeName: "Ravindra Suresh Patil",
    cooperativeId: "coop-3",
    cooperativeName: "Nashik District Cooperative Federation",
    nominatedBy: "Mr. Suresh Bhale, Secretary — Nashik DCF",
    submittedAt: "2026-09-08T11:00:00Z",
    updatedAt: "2026-09-14T15:00:00Z",
    status: "approved",
    timeline: [
      { id: "n-tl-1", timestamp: "2026-09-08T11:00:00Z", actor: "Nashik DCF", actorRole: "institution", action: "Nomination submitted", status: "submitted" },
      { id: "n-tl-2", timestamp: "2026-09-10T09:00:00Z", actor: "Nashik DCF", actorRole: "institution", action: "Cooperative review approved", status: "cooperative_review" },
      { id: "n-tl-3", timestamp: "2026-09-12T14:00:00Z", actor: "Dr. Meera Kulkarni", actorRole: "trainer", action: "Trainer review completed — approved", status: "trainer_review" },
      { id: "n-tl-4", timestamp: "2026-09-14T15:00:00Z", actor: "RICM Lucknow", actorRole: "institution", action: "Institution confirmed — batch allocated", status: "approved" },
    ],
    notes: "Priority nomination from state federation. Approved for Batch B.",
  },
];

export const MOCK_EXAM_REGISTRATIONS: ExamRegistration[] = [
  {
    id: "EXAM-REG-2026-00089",
    examId: "exam-coop-acc-001",
    examName: "Cooperative Accounting Certification",
    traineeId: "trainee-ravindra",
    traineeName: "Ravindra Suresh Patil",
    registeredAt: "2026-09-25T11:00:00Z",
    status: "slot_confirmed",
    slotDate: "2026-11-20",
    slotTime: "10:00 AM",
    slotVenue: "RICM Pune, Examination Centre",
    slotMode: "On-Campus",
    timeline: [
      { id: "er-tl-1", timestamp: "2026-09-25T11:00:00Z", actor: "Ravindra Suresh Patil", actorRole: "trainee", action: "Exam registration submitted" },
      { id: "er-tl-2", timestamp: "2026-09-25T11:30:00Z", actor: "System", actorRole: "system", action: "Eligibility verified — Eligible to appear" },
      { id: "er-tl-3", timestamp: "2026-09-27T09:00:00Z", actor: "NCCT Examination Cell", actorRole: "institution", action: "Slot confirmed — RICM Pune, 10:00 AM, Nov 20" },
    ],
    documents: [
      { type: "aadhaar", label: "Aadhaar Card", required: true, fileName: "aadhaar.pdf", fileSize: 245000, uploadedAt: "2026-09-25T10:55:00Z", status: "verified" },
      { type: "photo", label: "Passport Photo", required: true, fileName: "photo.jpg", fileSize: 52000, uploadedAt: "2026-09-25T10:56:00Z", status: "verified" },
    ],
  },
];

export const MOCK_UPCOMING_EVENTS: UpcomingEvent[] = [
  {
    id: "evt-1",
    type: "training",
    title: "PACS Digital Accounting — Batch 04",
    programmeOrExam: "PACS Digital Accounting",
    trainer: "Dr. Meera Kulkarni",
    date: "2026-11-10",
    time: "09:00 AM",
    venue: "Room 204, Block B, RICM Lucknow",
    mode: "Hybrid",
    status: "confirmed",
    applicationId: "CSA-2026-00389",
  },
  {
    id: "evt-2",
    type: "exam",
    title: "Cooperative Accounting Certification Exam",
    programmeOrExam: "CAC Examination",
    date: "2026-11-20",
    time: "10:00 AM",
    venue: "RICM Pune, Examination Centre",
    mode: "On-Campus",
    status: "confirmed",
    applicationId: "EXAM-REG-2026-00089",
  },
];
