import type { Course } from "@/lib/types";

export const courses: Course[] = [
  {
    id: "course-coop-mgmt-101",
    title: "Cooperative Management Fundamentals",
    category: "Governance",
    level: "Foundation",
    durationHours: 24,
    instructor: "Dr. Meenal Kulkarni",
    rating: 4.7,
    enrolled: 1842,
    description:
      "Understand the seven cooperative principles, board composition, and bylaws drafting through real primary-society case studies.",
    skills: ["Cooperative Management", "Governance", "Bylaws Drafting"],
  },
  {
    id: "course-dairy-ops-201",
    title: "Dairy Cooperative Operations",
    category: "Dairy & Agri-processing",
    level: "Intermediate",
    durationHours: 32,
    instructor: "Er. Rajendra Patil",
    rating: 4.8,
    enrolled: 963,
    description:
      "Hands-on modules on milk procurement software, FAT/SNF-based pricing, and route-level cold-chain quality control.",
    skills: ["Dairy Operations", "Quality Testing", "Logistics Planning"],
  },
  {
    id: "course-digital-marketing-101",
    title: "Digital Marketing for Cooperatives",
    category: "Marketing & Sales",
    level: "Foundation",
    durationHours: 18,
    instructor: "Ananya Bose",
    rating: 4.6,
    enrolled: 2210,
    description:
      "Build a low-budget digital presence: Instagram/WhatsApp catalogues, ONDC seller onboarding, and basic ad campaigns.",
    skills: ["Digital Marketing", "E-commerce", "Content Creation"],
  },
  {
    id: "course-data-analysis-coop",
    title: "Data Analysis for Cooperative Decision-Making",
    category: "Data & Analytics",
    level: "Intermediate",
    durationHours: 28,
    instructor: "Suresh Nair",
    rating: 4.5,
    enrolled: 731,
    description:
      "Use spreadsheets and dashboards to analyse member data, procurement trends, and default risk in credit societies.",
    skills: ["Data Analysis", "Spreadsheets", "Dashboarding"],
  },
  {
    id: "course-agri-credit-appraisal",
    title: "Agricultural Credit Appraisal & Risk",
    category: "Rural Finance",
    level: "Advanced",
    durationHours: 30,
    instructor: "Kavita Deshmukh",
    rating: 4.7,
    enrolled: 512,
    description:
      "Credit scoring for small and marginal farmers, NPA early-warning signals, and NABARD refinance documentation.",
    skills: ["Credit Appraisal", "Risk Management", "Compliance"],
  },
  {
    id: "course-handloom-design-cataloguing",
    title: "Handloom Product Design & Cataloguing",
    category: "Handloom & Handicrafts",
    level: "Foundation",
    durationHours: 20,
    instructor: "Farah Sheikh",
    rating: 4.6,
    enrolled: 486,
    description:
      "Digital cataloguing, GI-tag documentation, and pricing strategy for weaver cooperative product lines.",
    skills: ["Product Cataloguing", "GI Compliance", "Pricing Strategy"],
  },
  {
    id: "course-coop-bookkeeping",
    title: "Cooperative Bookkeeping with Tally",
    category: "Finance & Accounts",
    level: "Foundation",
    durationHours: 22,
    instructor: "Ramesh Iyer",
    rating: 4.4,
    enrolled: 1329,
    description:
      "Statutory registers, ledger reconciliation, and Tally-based double-entry bookkeeping for society accountants.",
    skills: ["Bookkeeping", "Tally", "Statutory Compliance"],
  },
  {
    id: "course-leadership-coop-boards",
    title: "Leadership for Cooperative Board Members",
    category: "Leadership",
    level: "Intermediate",
    durationHours: 16,
    instructor: "Dr. Meenal Kulkarni",
    rating: 4.5,
    enrolled: 604,
    description:
      "Conflict resolution, meeting facilitation, and succession planning for elected cooperative office bearers.",
    skills: ["Leadership", "Facilitation", "Governance"],
  },
  {
    id: "course-fpo-export-readiness",
    title: "FPO Export Readiness",
    category: "Agri Value Chains",
    level: "Advanced",
    durationHours: 26,
    instructor: "Suresh Nair",
    rating: 4.6,
    enrolled: 298,
    description:
      "Export documentation, quality certification, and buyer-linkage strategy for farmer producer organisations.",
    skills: ["Export Documentation", "Quality Certification", "Value Chains"],
  },
];
