import type { Job } from "@/lib/types";

export const jobs: Job[] = [
  {
    id: "job-dairy-supervisor-anand",
    title: "Dairy Procurement Supervisor",
    employer: "Amul Dairy Cooperative Union",
    location: "Anand, Gujarat",
    sector: "Dairy & Agri-processing",
    type: "Full-time",
    salaryRange: "₹22,000-₹28,000 / month",
    postedDaysAgo: 2,
    skillsRequired: ["Dairy Operations", "Quality Testing", "Logistics Planning"],
    description:
      "Oversee milk collection routes across 12 village societies, verify FAT/SNF readings, and coordinate cold-chain dispatch.",
    openings: 4,
  },
  {
    id: "job-society-accountant-pune",
    title: "Cooperative Society Accountant",
    employer: "Vaikunth Cooperative Credit Society",
    location: "Pune, Maharashtra",
    sector: "Rural Finance",
    type: "Full-time",
    salaryRange: "₹18,000-₹24,000 / month",
    postedDaysAgo: 5,
    skillsRequired: ["Bookkeeping", "Tally", "Statutory Compliance"],
    description:
      "Maintain society ledgers, prepare statutory registers, and support annual audit readiness for a 4,000-member PACS.",
    openings: 2,
  },
  {
    id: "job-digital-marketing-exec-kolkata",
    title: "Digital Marketing Executive",
    employer: "Bengal Handloom Weavers Cooperative",
    location: "Kolkata, West Bengal",
    sector: "Handloom & Handicrafts",
    type: "Full-time",
    salaryRange: "₹20,000-₹26,000 / month",
    postedDaysAgo: 1,
    skillsRequired: ["Digital Marketing", "E-commerce", "Content Creation"],
    description:
      "Run the cooperative's ONDC storefront, manage social catalogues, and grow direct-to-consumer sales for GI-tagged sarees.",
    openings: 1,
  },
  {
    id: "job-credit-officer-nagpur",
    title: "Agricultural Credit Officer",
    employer: "Vidarbha Farmers Cooperative Bank",
    location: "Nagpur, Maharashtra",
    sector: "Rural Finance",
    type: "Full-time",
    salaryRange: "₹25,000-₹32,000 / month",
    postedDaysAgo: 8,
    skillsRequired: ["Credit Appraisal", "Risk Management", "Compliance"],
    description:
      "Appraise crop loan applications, monitor NPA accounts, and prepare NABARD refinance claims for 6 branch societies.",
    openings: 3,
  },
  {
    id: "job-fpo-manager-indore",
    title: "FPO Operations Manager",
    employer: "Malwa Farmer Producer Company Ltd.",
    location: "Indore, Madhya Pradesh",
    sector: "Agri Value Chains",
    type: "Full-time",
    salaryRange: "₹30,000-₹40,000 / month",
    postedDaysAgo: 3,
    skillsRequired: ["Export Documentation", "Value Chains", "Data Analysis"],
    description:
      "Lead aggregation and warehousing operations for a 2,200-farmer producer company exporting soybean and wheat.",
    openings: 1,
  },
  {
    id: "job-fisheries-coord-kochi",
    title: "Fisheries Cooperative Coordinator",
    employer: "Kerala State Fisheries Cooperative Federation",
    location: "Kochi, Kerala",
    sector: "Fisheries & Aquaculture",
    type: "Contract",
    salaryRange: "₹19,000-₹23,000 / month",
    postedDaysAgo: 6,
    skillsRequired: ["Cooperative Management", "Governance"],
    description:
      "Coordinate catch aggregation schedules and welfare scheme disbursal across 9 coastal fisheries societies.",
    openings: 2,
  },
  {
    id: "job-mis-analyst-delhi",
    title: "MIS & Data Analyst - Cooperative Sector",
    employer: "National Cooperative Development Corporation",
    location: "New Delhi",
    sector: "Data & Analytics",
    type: "Full-time",
    salaryRange: "₹35,000-₹45,000 / month",
    postedDaysAgo: 4,
    skillsRequired: ["Data Analysis", "Dashboarding", "Spreadsheets"],
    description:
      "Build state-level dashboards tracking cooperative registration, training completion, and employment outcomes.",
    openings: 2,
  },
  {
    id: "job-apprentice-coop-secretary-jaipur",
    title: "Apprentice Cooperative Society Secretary",
    employer: "Rajasthan State Cooperative Union",
    location: "Jaipur, Rajasthan",
    sector: "Cooperative Governance",
    type: "Apprenticeship",
    salaryRange: "₹12,000 / month stipend",
    postedDaysAgo: 10,
    skillsRequired: ["Cooperative Management", "Bylaws Drafting"],
    description:
      "12-month apprenticeship shadowing a senior society secretary across member relations, meetings, and record-keeping.",
    openings: 6,
  },
];
