import type { Programme } from "@/lib/types";

export const programmes: Programme[] = [
  {
    id: "prog-coop-mgmt-fundamentals",
    title: "Cooperative Management Fundamentals",
    sector: "Cooperative Governance",
    institution: "National Cooperative Union of India Training Centre, Delhi",
    level: "Foundation",
    mode: "Blended",
    durationWeeks: 8,
    seatsTotal: 60,
    seatsFilled: 47,
    startDate: "2026-10-12",
    description:
      "Core principles of cooperative governance, member ownership, bylaws, and democratic decision-making for society secretaries and board members.",
    tags: ["Governance", "Bylaws", "Member Relations"],
  },
  {
    id: "prog-dairy-coop-ops",
    title: "Dairy Cooperative Operations",
    sector: "Dairy & Agri-processing",
    institution: "Institute of Rural Management, Anand",
    level: "Intermediate",
    mode: "In-person",
    durationWeeks: 10,
    seatsTotal: 40,
    seatsFilled: 40,
    startDate: "2026-11-02",
    description:
      "Milk procurement, cold-chain logistics, quality testing (FAT/SNF), and route optimisation for primary dairy cooperative societies.",
    tags: ["Dairy", "Cold Chain", "Quality Testing", "Logistics"],
  },
  {
    id: "prog-agri-credit-coop",
    title: "Agricultural Credit Cooperative Management",
    sector: "Rural Finance",
    institution: "Vaikunth Mehta National Institute of Cooperative Management, Pune",
    level: "Advanced",
    mode: "Blended",
    durationWeeks: 12,
    seatsTotal: 35,
    seatsFilled: 22,
    startDate: "2026-10-26",
    description:
      "Credit appraisal, NPA management, PACS digitisation, and RBI/NABARD compliance for primary agricultural credit societies.",
    tags: ["Rural Credit", "PACS", "NABARD Compliance", "NPA Management"],
  },
  {
    id: "prog-handloom-coop-enterprise",
    title: "Handloom & Handicraft Cooperative Enterprise",
    sector: "Handloom & Handicrafts",
    institution: "National Institute of Fashion Technology (Cooperative Cell), Kolkata",
    level: "Foundation",
    mode: "In-person",
    durationWeeks: 6,
    seatsTotal: 50,
    seatsFilled: 31,
    startDate: "2026-10-19",
    description:
      "Weaver cooperative formation, design cataloguing, GI-tag compliance, and e-commerce onboarding for handloom producer societies.",
    tags: ["Handloom", "GI Tagging", "E-commerce"],
  },
  {
    id: "prog-digital-marketing-coop",
    title: "Digital Marketing for Cooperatives",
    sector: "Marketing & Sales",
    institution: "Laxmanrao Inamdar National Academy for Cooperative Research, Gandhinagar",
    level: "Intermediate",
    mode: "Online",
    durationWeeks: 5,
    seatsTotal: 100,
    seatsFilled: 68,
    startDate: "2026-10-06",
    description:
      "Social media presence, ONDC onboarding, WhatsApp commerce, and performance marketing basics for cooperative retail brands.",
    tags: ["Digital Marketing", "ONDC", "E-commerce", "Branding"],
  },
  {
    id: "prog-fpo-value-chain",
    title: "Farmer Producer Organisation (FPO) Value Chain Management",
    sector: "Agri Value Chains",
    institution: "Institute of Rural Management, Anand",
    level: "Advanced",
    mode: "Blended",
    durationWeeks: 14,
    seatsTotal: 30,
    seatsFilled: 18,
    startDate: "2026-11-16",
    description:
      "End-to-end aggregation, warehousing, FPO-industry linkages, and export documentation for producer company managers.",
    tags: ["FPO", "Warehousing", "Export Readiness"],
  },
  {
    id: "prog-coop-bookkeeping",
    title: "Cooperative Bookkeeping & Statutory Audit Readiness",
    sector: "Finance & Accounts",
    institution: "National Cooperative Union of India Training Centre, Delhi",
    level: "Foundation",
    mode: "Online",
    durationWeeks: 6,
    seatsTotal: 80,
    seatsFilled: 52,
    startDate: "2026-10-13",
    description:
      "Double-entry bookkeeping, statutory registers, cooperative audit norms, and Tally-based accounting for society accountants.",
    tags: ["Accounting", "Audit", "Tally", "Compliance"],
  },
  {
    id: "prog-fisheries-coop",
    title: "Fisheries Cooperative Society Management",
    sector: "Fisheries & Aquaculture",
    institution: "Central Institute of Fisheries Education Extension Cell, Mumbai",
    level: "Intermediate",
    mode: "In-person",
    durationWeeks: 9,
    seatsTotal: 45,
    seatsFilled: 29,
    startDate: "2026-11-09",
    description:
      "Catch aggregation, cold storage management, harbour operations, and welfare scheme administration for fisheries societies.",
    tags: ["Fisheries", "Cold Storage", "Welfare Schemes"],
  },
];
