// =============================================================================
// Programme Mock Data — 20+ rich, cooperative-oriented programmes
// =============================================================================
import type { Programme, Trainer, Institution, Cooperative, CertificationExam } from "@/types/programme";

export const mockTrainers: Trainer[] = [
  {
    id: "trainer-1",
    name: "Dr. Anand Deshmukh",
    title: "Senior Faculty — Cooperative Management",
    institution: "VAMNICOM Pune",
    specializations: ["Cooperative Management", "PACS Accounting", "Cooperative Law"],
    experience: "18 years",
    email: "anand.deshmukh@vamnicom.ac.in",
    rating: 4.8,
    bio: "Dr. Deshmukh has trained over 3,000 cooperative professionals across Maharashtra and Gujarat. Expert in PACS modernisation and digital cooperative governance.",
  },
  {
    id: "trainer-2",
    name: "Dr. Meera Kulkarni",
    title: "Associate Professor — Financial Management",
    institution: "RICM Pune",
    specializations: ["Financial Management", "Bookkeeping", "Audit"],
    experience: "12 years",
    email: "meera.kulkarni@ricm-pune.ac.in",
    rating: 4.7,
    bio: "Expert in cooperative financial systems with special focus on rural credit societies. Authored 3 textbooks on PACS digital accounting.",
  },
  {
    id: "trainer-3",
    name: "Prof. Rajkumar Singh",
    title: "Faculty — Dairy Cooperative Operations",
    institution: "NDRI Karnal",
    specializations: ["Dairy Operations", "Cold Chain", "Quality Assurance"],
    experience: "15 years",
    email: "rk.singh@ndri.res.in",
    rating: 4.6,
    bio: "Former Amul quality manager with deep expertise in dairy cooperative operations and modern milk testing protocols.",
  },
  {
    id: "trainer-4",
    name: "Ms. Sunita Bhat",
    title: "Faculty — Digital Literacy",
    institution: "ICM Guwahati",
    specializations: ["Digital Literacy", "Digital Payments", "E-Commerce"],
    experience: "8 years",
    email: "sunita.bhat@icm-guwahati.ac.in",
    rating: 4.5,
    bio: "Pioneer in rural digital literacy programmes across North-East India. Trained over 1,500 women cooperatives in digital finance.",
  },
  {
    id: "trainer-5",
    name: "Dr. Vikram Rao",
    title: "Director & Senior Faculty",
    institution: "VAMNICOM Pune",
    specializations: ["Cooperative Governance", "Leadership", "Rural Entrepreneurship"],
    experience: "22 years",
    email: "vikram.rao@vamnicom.ac.in",
    rating: 4.9,
    bio: "Nationally recognized expert in cooperative governance. Served on the National Cooperative Policy Committee. Trainer to 5,000+ cooperative leaders.",
  },
  {
    id: "trainer-6",
    name: "Prof. Geeta Sharma",
    title: "Faculty — Rural Credit",
    institution: "RICM Lucknow",
    specializations: ["Rural Credit", "KCC", "Microfinance"],
    experience: "10 years",
    email: "geeta.sharma@ricm-lucknow.ac.in",
    rating: 4.4,
    bio: "Specialist in Kisan Credit Card operations and rural credit policy. Trains PACS staff on loan management and recovery.",
  },
  {
    id: "trainer-7",
    name: "Dr. K. Ramaswamy",
    title: "Faculty — Supply Chain & Logistics",
    institution: "ICM Hyderabad",
    specializations: ["Supply Chain", "Agri Logistics", "Marketing"],
    experience: "16 years",
    email: "k.ramaswamy@icm-hyd.ac.in",
    rating: 4.6,
    bio: "Expert in cooperative supply chain and agri-marketing. Consulted for 50+ cooperative federations across Andhra Pradesh and Telangana.",
  },
  {
    id: "trainer-8",
    name: "Ms. Anjali Mehta",
    title: "Faculty — Women Enterprise Development",
    institution: "VAMNICOM Pune",
    specializations: ["Women Empowerment", "SHG", "Enterprise Development"],
    experience: "9 years",
    email: "anjali.mehta@vamnicom.ac.in",
    rating: 4.7,
    bio: "Champion of women-led cooperative enterprises. Facilitated formation of 200+ SHG cooperatives across Maharashtra.",
  },
];

export const mockInstitutions: Institution[] = [
  { id: "inst-1", name: "Vaikunth Mehta National Institute of Cooperative Management", shortName: "VAMNICOM", type: "VAMNICOM", state: "Maharashtra", district: "Pune", address: "University Road, Pune 411 007", website: "www.vamnicom.ac.in", accreditation: "NAAC A+" },
  { id: "inst-2", name: "Regional Institute of Cooperative Management, Pune", shortName: "RICM Pune", type: "RICM", state: "Maharashtra", district: "Pune", address: "Symbiosis Road, Pune 411 004", website: "www.ricm-pune.ac.in", accreditation: "NCCT Certified" },
  { id: "inst-3", name: "Regional Institute of Cooperative Management, Lucknow", shortName: "RICM Lucknow", type: "RICM", state: "Uttar Pradesh", district: "Lucknow", address: "Sector 4, Indira Nagar, Lucknow", website: "www.ricm-lucknow.ac.in", accreditation: "NCCT Certified" },
  { id: "inst-4", name: "Institute of Cooperative Management, Bhopal", shortName: "ICM Bhopal", type: "ICM", state: "Madhya Pradesh", district: "Bhopal", address: "Shyamla Hills, Bhopal 462 002", website: "www.icm-bhopal.ac.in", accreditation: "NCCT Certified" },
  { id: "inst-5", name: "Institute of Cooperative Management, Guwahati", shortName: "ICM Guwahati", type: "ICM", state: "Assam", district: "Guwahati", address: "Six Mile, Guwahati 781 022", website: "www.icm-guwahati.ac.in", accreditation: "NCCT Certified" },
  { id: "inst-6", name: "Institute of Cooperative Management, Hyderabad", shortName: "ICM Hyderabad", type: "ICM", state: "Telangana", district: "Hyderabad", address: "Masab Tank, Hyderabad 500 028", website: "www.icm-hyd.ac.in", accreditation: "NCCT Certified" },
  { id: "inst-7", name: "Institute of Cooperative Management, Anand", shortName: "ICM Anand", type: "ICM", state: "Gujarat", district: "Anand", address: "Vallabh Vidyanagar, Anand 388 120", website: "www.icm-anand.ac.in", accreditation: "NCCT Certified" },
  { id: "inst-8", name: "National Dairy Research Institute", shortName: "NDRI", type: "Other", state: "Haryana", district: "Karnal", address: "NDRI Campus, Karnal 132 001", website: "www.ndri.res.in", accreditation: "ICAR Accredited" },
];

export const mockCooperatives: Cooperative[] = [
  { id: "coop-1", name: "Kaira Milk Producers Cooperative Union", type: "Dairy", state: "Gujarat", district: "Anand", memberCount: 1800 },
  { id: "coop-2", name: "Haveli Taluka PACS", type: "Credit", state: "Maharashtra", district: "Pune", memberCount: 650 },
  { id: "coop-3", name: "Nashik District Cooperative Federation", type: "Multi-purpose", state: "Maharashtra", district: "Nashik", memberCount: 3200 },
  { id: "coop-4", name: "Pune Dairy Cooperative Society", type: "Dairy", state: "Maharashtra", district: "Pune", memberCount: 980 },
  { id: "coop-5", name: "Women SHG Cooperative Federation, Nashik", type: "SHG", state: "Maharashtra", district: "Nashik", memberCount: 420 },
  { id: "coop-6", name: "Ahmedabad District Central Cooperative Bank", type: "Banking", state: "Gujarat", district: "Ahmedabad", memberCount: 5000 },
  { id: "coop-7", name: "Bhopal Farmers Cooperative Society", type: "Agriculture", state: "Madhya Pradesh", district: "Bhopal", memberCount: 750 },
  { id: "coop-8", name: "Jorhat Tea Growers Cooperative", type: "Agriculture", state: "Assam", district: "Jorhat", memberCount: 300 },
  { id: "coop-9", name: "Hyderabad Urban Cooperative Bank", type: "Banking", state: "Telangana", district: "Hyderabad", memberCount: 2400 },
  { id: "coop-10", name: "Karnataka Silk Weavers Cooperative", type: "Handloom", state: "Karnataka", district: "Mysuru", memberCount: 560 },
];

const baseEligibilityRules = [
  {
    field: "education",
    label: "Minimum Education",
    operator: "in" as const,
    value: ["10th Pass", "12th Pass", "Graduate", "Post-Graduate"],
    description: "Minimum 10th standard pass required",
  },
  {
    field: "cooperativeMembership",
    label: "Cooperative Membership",
    operator: "exists" as const,
    value: "yes",
    description: "Must be a member of a registered cooperative society",
  },
  {
    field: "age",
    label: "Age Requirement",
    operator: "gte" as const,
    value: 18,
    description: "Must be at least 18 years old",
  },
];

export const MOCK_PROGRAMMES: Programme[] = [
  {
    id: "prog-coop-mgmt-001",
    title: "Cooperative Management Fundamentals",
    shortDescription: "Comprehensive foundation programme covering cooperative principles, governance and financial management for PACS staff.",
    fullDescription: "This flagship VAMNICOM programme provides an end-to-end introduction to cooperative management — from Rochdale principles and the MSCS Act, to day-to-day governance, member relations and financial record keeping. Ideal for newly appointed PACS secretaries and junior cooperative managers.",
    type: "training",
    category: "Cooperative Management",
    institution: "VAMNICOM Pune",
    institutionId: "inst-1",
    location: "Pune, Maharashtra",
    state: "Maharashtra",
    district: "Pune",
    mode: "On-Campus",
    language: ["English", "Marathi", "Hindi"],
    startDate: "2026-11-05",
    endDate: "2026-11-30",
    duration: 4,
    durationUnit: "weeks",
    registrationDeadline: "2026-10-25",
    totalSeats: 40,
    availableSeats: 12,
    level: "Beginner",
    certificateType: "Certificate",
    skills: ["Cooperative Law", "PACS Governance", "Member Relations", "Financial Management", "Audit Basics"],
    eligibility: ["10th pass minimum", "Cooperative member", "Age 18+"],
    eligibilityRules: baseEligibilityRules,
    hostelAvailable: true,
    mealAvailable: true,
    transportAvailable: false,
    trainerIds: ["trainer-1", "trainer-5"],
    curriculum: [
      { week: 1, title: "Cooperative Principles & History", topics: ["Rochdale Pioneers", "ICA Principles", "Cooperative Types in India", "MSCS Act Overview"], hours: 30 },
      { week: 2, title: "PACS Governance & Administration", topics: ["Board Structure", "General Body Meetings", "Election Procedures", "Bylaws & Amendments"], hours: 30 },
      { week: 3, title: "Financial Management", topics: ["Cash Book", "Ledger Maintenance", "Balance Sheet", "Profit & Loss"], hours: 30 },
      { week: 4, title: "Member Services & Audit", topics: ["Loan Appraisal", "Recovery", "Internal Audit", "Statutory Compliance"], hours: 30 },
    ],
    learningOutcomes: [
      "Understand the legal framework governing cooperatives in India",
      "Manage PACS governance processes including board meetings and elections",
      "Maintain financial records and prepare basic reports",
      "Conduct member services and handle complaints effectively",
    ],
    documentsRequired: ["Aadhaar Card", "Education Certificate", "Cooperative Membership Proof", "Passport Photo", "Employment Proof"],
    fee: 2500,
    isFree: false,
    status: "active",
    featured: true,
    recommended: true,
    applicationCount: 28,
    rating: 4.8,
    tags: ["cooperative", "PACS", "management", "governance", "foundation"],
  },
  {
    id: "prog-pacs-accounting-002",
    title: "PACS Digital Accounting",
    shortDescription: "Hands-on digital accounting programme for PACS using Tally Prime and government-approved cooperative accounting software.",
    fullDescription: "Learn to maintain PACS accounts digitally using Tally Prime ERP and the government-approved NAFCOB accounting system. Covers voucher entry, bank reconciliation, trial balance, audit reports, and integration with the National Cooperative Database. Highly relevant for PACS modernisation drive.",
    type: "training",
    category: "Finance & Accounting",
    institution: "RICM Lucknow",
    institutionId: "inst-3",
    location: "Lucknow, Uttar Pradesh",
    state: "Uttar Pradesh",
    district: "Lucknow",
    mode: "Hybrid",
    language: ["Hindi", "English"],
    startDate: "2026-11-10",
    endDate: "2026-12-05",
    duration: 4,
    durationUnit: "weeks",
    registrationDeadline: "2026-10-28",
    totalSeats: 35,
    availableSeats: 8,
    level: "Intermediate",
    certificateType: "Certificate",
    skills: ["Tally Prime", "PACS Accounting", "Bank Reconciliation", "Financial Reporting", "Digital Records"],
    eligibility: ["12th pass or above", "Cooperative member or employee", "Basic computer knowledge"],
    eligibilityRules: [
      {
        field: "education",
        label: "Minimum Education",
        operator: "in",
        value: ["12th Pass", "Graduate", "Post-Graduate"],
        description: "Minimum 12th standard pass required",
      },
      ...baseEligibilityRules.slice(1),
    ],
    hostelAvailable: true,
    mealAvailable: true,
    transportAvailable: true,
    trainerIds: ["trainer-2", "trainer-1"],
    curriculum: [
      { week: 1, title: "Digital Accounting Fundamentals", topics: ["Double Entry System", "Chart of Accounts", "Tally Prime Setup", "Company Creation"], hours: 30 },
      { week: 2, title: "Day-to-Day Transactions", topics: ["Voucher Entry", "Bank Entries", "Loan Disbursements", "Recovery Entries"], hours: 30 },
      { week: 3, title: "Reports & Reconciliation", topics: ["Trial Balance", "Bank Reconciliation", "Outstanding Reports", "Aging Analysis"], hours: 30 },
      { week: 4, title: "Statutory & Audit Reports", topics: ["Annual Accounts", "Audit Preparation", "NAFCOB Integration", "Data Export"], hours: 30 },
    ],
    learningOutcomes: [
      "Set up and operate Tally Prime for PACS accounting",
      "Record all types of cooperative transactions accurately",
      "Generate financial reports required for annual audit",
      "Integrate accounts with national cooperative databases",
    ],
    documentsRequired: ["Aadhaar Card", "Education Certificate", "Cooperative Membership Proof", "Passport Photo"],
    fee: 3000,
    isFree: false,
    status: "active",
    featured: true,
    recommended: true,
    applicationCount: 27,
    rating: 4.7,
    tags: ["accounting", "Tally", "PACS", "digital", "finance"],
  },
  {
    id: "prog-dairy-ops-003",
    title: "Dairy Cooperative Operations",
    shortDescription: "Operational training for dairy cooperative staff covering milk collection, testing, processing and quality control.",
    fullDescription: "A comprehensive 5-week programme covering the full operational cycle of a dairy cooperative — from farm-level milk collection and initial testing, through chilling center management, to final quality certification. Includes practical sessions at a model dairy cooperative facility.",
    type: "training",
    category: "Dairy & Agriculture",
    institution: "VAMNICOM Pune",
    institutionId: "inst-1",
    location: "Pune, Maharashtra",
    state: "Maharashtra",
    district: "Pune",
    mode: "On-Campus",
    language: ["English", "Marathi", "Hindi"],
    startDate: "2026-11-15",
    endDate: "2026-12-20",
    duration: 5,
    durationUnit: "weeks",
    registrationDeadline: "2026-11-01",
    totalSeats: 30,
    availableSeats: 18,
    level: "Intermediate",
    certificateType: "Certificate",
    skills: ["Milk Testing", "Quality Control", "Chilling Operations", "Cooperative Supply Chain", "HACCP Basics"],
    eligibility: ["10th pass minimum", "Dairy cooperative member", "Age 18-45"],
    eligibilityRules: baseEligibilityRules,
    hostelAvailable: true,
    mealAvailable: true,
    transportAvailable: true,
    trainerIds: ["trainer-3"],
    curriculum: [
      { week: 1, title: "Dairy Cooperative Structure", topics: ["Village DCS Operations", "Milk Collection Schedules", "Member Payment Systems"], hours: 25 },
      { week: 2, title: "Milk Testing & Quality", topics: ["SNF Testing", "Fat Testing", "Adulteration Detection", "Quality Standards"], hours: 25 },
      { week: 3, title: "Chilling & Processing", topics: ["BMC Operations", "Cold Chain Management", "Pasteurization Basics"], hours: 25 },
      { week: 4, title: "Cooperative Management", topics: ["Member Services", "Route Planning", "Cost Management"], hours: 25 },
      { week: 5, title: "Field Practice & Assessment", topics: ["Live DCS Visit", "Case Studies", "Final Assessment"], hours: 25 },
    ],
    learningOutcomes: [
      "Operate milk collection centres and testing equipment",
      "Maintain quality standards throughout the dairy supply chain",
      "Manage Bulk Milk Chilling unit operations effectively",
      "Handle member payment and grievance systems",
    ],
    documentsRequired: ["Aadhaar Card", "Education Certificate", "Cooperative Membership Proof", "Passport Photo", "Medical Fitness Certificate"],
    fee: 4000,
    isFree: false,
    status: "active",
    featured: false,
    recommended: false,
    applicationCount: 12,
    rating: 4.6,
    tags: ["dairy", "milk", "quality", "operations", "cooperative"],
  },
  {
    id: "prog-coop-governance-004",
    title: "Cooperative Governance & Audit",
    shortDescription: "Advanced programme on cooperative governance frameworks, statutory audit procedures and regulatory compliance.",
    fullDescription: "Designed for senior cooperative officers and board members, this advanced programme covers the complete governance lifecycle — from conducting general body meetings and maintaining statutory books to managing statutory audits and responding to registrar inspections. Includes mock audit practicals.",
    type: "training",
    category: "Governance & Compliance",
    institution: "ICM Bhopal",
    institutionId: "inst-4",
    location: "Bhopal, Madhya Pradesh",
    state: "Madhya Pradesh",
    district: "Bhopal",
    mode: "Hybrid",
    language: ["Hindi", "English"],
    startDate: "2026-12-01",
    endDate: "2026-12-21",
    duration: 3,
    durationUnit: "weeks",
    registrationDeadline: "2026-11-15",
    totalSeats: 45,
    availableSeats: 22,
    level: "Advanced",
    certificateType: "Certificate",
    skills: ["Cooperative Governance", "Statutory Audit", "Regulatory Compliance", "Board Management", "Risk Assessment"],
    eligibility: ["Graduate minimum", "2+ years cooperative experience", "Board member or senior officer"],
    eligibilityRules: [
      { field: "education", label: "Minimum Education", operator: "in", value: ["Graduate", "Post-Graduate"], description: "Graduate qualification required" },
      { field: "experience", label: "Work Experience", operator: "gte", value: 2, description: "Minimum 2 years in cooperative sector" },
      { field: "cooperativeMembership", label: "Cooperative Membership", operator: "exists", value: "yes", description: "Must be a cooperative member or employee" },
    ],
    hostelAvailable: true,
    mealAvailable: true,
    transportAvailable: false,
    trainerIds: ["trainer-5", "trainer-1"],
    curriculum: [
      { week: 1, title: "Legal Framework & Governance", topics: ["Model Byelaws", "Registrar Powers", "Inspection Procedures", "AGM Conduct"], hours: 35 },
      { week: 2, title: "Audit & Compliance", topics: ["Audit Manual", "Audit Classification", "Surcharge Proceedings", "Mock Audit"], hours: 35 },
      { week: 3, title: "Risk & Modernisation", topics: ["Internal Controls", "IT Governance", "Compliance Calendar", "Case Studies"], hours: 35 },
    ],
    learningOutcomes: [
      "Conduct statutory audit with confidence",
      "Maintain required governance records and minute books",
      "Respond to registrar inspections professionally",
      "Implement internal control systems in cooperatives",
    ],
    documentsRequired: ["Aadhaar Card", "Education Certificate", "Experience Letter", "Cooperative Membership Proof", "Passport Photo"],
    fee: 3500,
    isFree: false,
    status: "active",
    featured: false,
    recommended: false,
    applicationCount: 23,
    rating: 4.5,
    tags: ["governance", "audit", "compliance", "advanced"],
  },
  {
    id: "prog-digital-lit-005",
    title: "Digital Literacy for Rural Cooperatives",
    shortDescription: "Foundational digital skills programme for cooperative staff with no prior computer experience.",
    fullDescription: "A beginner-friendly programme covering smartphone usage, digital payments, basic email and MS Office, and government digital services. Conducted in regional language with hands-on device training. Specifically designed for rural cooperative members from low-digital-literacy backgrounds.",
    type: "digital-literacy",
    category: "Digital Literacy",
    institution: "ICM Guwahati",
    institutionId: "inst-5",
    location: "Guwahati, Assam",
    state: "Assam",
    district: "Guwahati",
    mode: "On-Campus",
    language: ["Assamese", "Hindi", "English"],
    startDate: "2026-11-20",
    endDate: "2026-12-19",
    duration: 4,
    durationUnit: "weeks",
    registrationDeadline: "2026-11-05",
    totalSeats: 50,
    availableSeats: 31,
    level: "Beginner",
    certificateType: "Certificate",
    skills: ["Digital Payments", "Smartphone Usage", "Email", "MS Office Basics", "E-Government Services"],
    eligibility: ["8th pass minimum", "Cooperative member", "Age 18+"],
    eligibilityRules: [
      { field: "education", label: "Minimum Education", operator: "in", value: ["8th Pass", "10th Pass", "12th Pass", "Graduate", "Post-Graduate"], description: "8th standard minimum" },
      ...baseEligibilityRules.slice(1),
    ],
    hostelAvailable: true,
    mealAvailable: true,
    transportAvailable: false,
    trainerIds: ["trainer-4"],
    curriculum: [
      { week: 1, title: "Digital Basics", topics: ["Smartphone Essentials", "Internet Safety", "WhatsApp for Business", "Google Maps"], hours: 25 },
      { week: 2, title: "Digital Payments", topics: ["UPI & BHIM", "PMJDY Accounts", "Online Banking", "DigiLocker"], hours: 25 },
      { week: 3, title: "Government Digital Services", topics: ["Aadhaar Services", "UMANG App", "Kisan App", "e-NAM"], hours: 25 },
      { week: 4, title: "Cooperative Digital Tools", topics: ["NCCS Portal", "SMS-based Updates", "Digital Records", "Certification"], hours: 25 },
    ],
    learningOutcomes: [
      "Use smartphones confidently for cooperative operations",
      "Conduct and receive digital payments via UPI",
      "Access government services through digital portals",
      "Use cooperative digital platforms for member management",
    ],
    documentsRequired: ["Aadhaar Card", "Cooperative Membership Proof", "Passport Photo"],
    fee: 0,
    isFree: true,
    status: "active",
    featured: false,
    recommended: false,
    applicationCount: 19,
    rating: 4.3,
    tags: ["digital", "literacy", "beginner", "rural", "free"],
  },
  {
    id: "prog-coop-finance-006",
    title: "Cooperative Financial Management",
    shortDescription: "Strategic financial management skills for mid-level cooperative officers covering budgeting, investment and financial analysis.",
    fullDescription: "An intermediate-to-advanced programme covering cooperative financial strategy — from capital mobilisation and investment management to financial analysis and performance measurement. Combines classroom instruction with financial modelling exercises using real cooperative data.",
    type: "training",
    category: "Finance & Accounting",
    institution: "VAMNICOM Pune",
    institutionId: "inst-1",
    location: "Pune, Maharashtra",
    state: "Maharashtra",
    district: "Pune",
    mode: "On-Campus",
    language: ["English", "Marathi"],
    startDate: "2026-12-05",
    endDate: "2026-12-26",
    duration: 3,
    durationUnit: "weeks",
    registrationDeadline: "2026-11-20",
    totalSeats: 35,
    availableSeats: 14,
    level: "Intermediate",
    certificateType: "Diploma",
    skills: ["Financial Analysis", "Budgeting", "Investment Management", "Performance Metrics", "Financial Modelling"],
    eligibility: ["Graduate minimum", "Cooperative employment", "1+ year experience"],
    eligibilityRules: [
      { field: "education", label: "Minimum Education", operator: "in", value: ["Graduate", "Post-Graduate"], description: "Graduate qualification required" },
      { field: "cooperativeMembership", label: "Cooperative Employment", operator: "exists", value: "yes", description: "Must be employed in a cooperative" },
    ],
    hostelAvailable: true,
    mealAvailable: true,
    transportAvailable: false,
    trainerIds: ["trainer-2", "trainer-5"],
    curriculum: [
      { week: 1, title: "Capital & Funding", topics: ["Share Capital", "Reserves", "Borrowing Policy", "Capital Adequacy"], hours: 35 },
      { week: 2, title: "Financial Analysis", topics: ["Ratio Analysis", "Cash Flow", "Profitability", "Risk Management"], hours: 35 },
      { week: 3, title: "Budgeting & Planning", topics: ["Annual Budget", "Variance Analysis", "Financial Projections", "Strategic Finance"], hours: 35 },
    ],
    learningOutcomes: [
      "Prepare and manage annual cooperative budget",
      "Analyse financial performance using ratios and metrics",
      "Design investment strategy for cooperative surplus funds",
      "Present financial reports to board and auditors",
    ],
    documentsRequired: ["Aadhaar Card", "Education Certificate", "Employment Letter", "Cooperative Membership Proof", "Passport Photo"],
    fee: 5000,
    isFree: false,
    status: "active",
    featured: true,
    recommended: true,
    applicationCount: 21,
    rating: 4.8,
    tags: ["finance", "management", "diploma", "intermediate"],
  },
  {
    id: "prog-shg-007",
    title: "SHG Enterprise Development",
    shortDescription: "Practical programme for SHG leaders on converting self-help groups into productive cooperative enterprises.",
    fullDescription: "Designed specifically for women SHG leaders and cooperative federation officers, this programme covers the complete journey from SHG to cooperative enterprise — including legal registration, product development, packaging, FSSAI compliance and market linkage.",
    type: "skill-development",
    category: "Enterprise Development",
    institution: "VAMNICOM Pune",
    institutionId: "inst-1",
    location: "Pune, Maharashtra",
    state: "Maharashtra",
    district: "Pune",
    mode: "On-Campus",
    language: ["Marathi", "Hindi", "English"],
    startDate: "2026-11-25",
    endDate: "2026-12-06",
    duration: 2,
    durationUnit: "weeks",
    registrationDeadline: "2026-11-10",
    totalSeats: 60,
    availableSeats: 35,
    level: "Beginner",
    certificateType: "Certificate",
    skills: ["Enterprise Management", "Product Development", "Marketing", "FSSAI Compliance", "Financial Planning"],
    eligibility: ["8th pass minimum", "SHG or cooperative member", "Women entrepreneurs preferred"],
    eligibilityRules: [
      { field: "education", label: "Minimum Education", operator: "in", value: ["8th Pass", "10th Pass", "12th Pass", "Graduate", "Post-Graduate"], description: "8th standard minimum" },
      ...baseEligibilityRules.slice(1),
    ],
    hostelAvailable: true,
    mealAvailable: true,
    transportAvailable: false,
    trainerIds: ["trainer-8"],
    curriculum: [
      { week: 1, title: "SHG to Cooperative", topics: ["Legal Registration", "Business Plan", "Product Ideas", "Market Research"], hours: 40 },
      { week: 2, title: "Operations & Marketing", topics: ["Product Development", "Packaging", "FSSAI", "Market Linkages", "Online Sales"], hours: 40 },
    ],
    learningOutcomes: [
      "Convert SHG into a registered cooperative enterprise",
      "Develop marketable products with proper compliance",
      "Establish market linkages including online channels",
      "Maintain basic business accounts and records",
    ],
    documentsRequired: ["Aadhaar Card", "SHG Registration Certificate", "Passport Photo"],
    fee: 1500,
    isFree: false,
    status: "active",
    featured: false,
    recommended: false,
    applicationCount: 25,
    rating: 4.5,
    tags: ["SHG", "women", "enterprise", "cooperative"],
  },
  {
    id: "prog-rural-ent-008",
    title: "Rural Entrepreneurship Essentials",
    shortDescription: "Foundation entrepreneurship programme for cooperative members aspiring to start rural enterprises.",
    fullDescription: "A practical entrepreneurship programme that guides cooperative members through opportunity identification, business plan preparation, government scheme application, and access to cooperative credit for rural enterprise. Includes mentorship sessions with successful rural entrepreneurs.",
    type: "skill-development",
    category: "Entrepreneurship",
    institution: "ICM Anand",
    institutionId: "inst-7",
    location: "Anand, Gujarat",
    state: "Gujarat",
    district: "Anand",
    mode: "On-Campus",
    language: ["Gujarati", "Hindi", "English"],
    startDate: "2026-12-08",
    endDate: "2026-12-26",
    duration: 3,
    durationUnit: "weeks",
    registrationDeadline: "2026-11-22",
    totalSeats: 40,
    availableSeats: 22,
    level: "Beginner",
    certificateType: "Certificate",
    skills: ["Business Planning", "Rural Finance", "Market Analysis", "Government Schemes", "Cooperative Credit"],
    eligibility: ["10th pass minimum", "Cooperative member", "Age 21-45"],
    eligibilityRules: baseEligibilityRules,
    hostelAvailable: false,
    mealAvailable: true,
    transportAvailable: false,
    trainerIds: ["trainer-5"],
    curriculum: [
      { week: 1, title: "Opportunity Identification", topics: ["Market Research", "Rural Demand Analysis", "Value Chain Mapping"], hours: 30 },
      { week: 2, title: "Business Planning", topics: ["Business Plan Writing", "Financial Projections", "Risk Assessment"], hours: 30 },
      { week: 3, title: "Access to Finance", topics: ["Government Schemes", "PMEGP", "Cooperative Loans", "Pitch to Bank"], hours: 30 },
    ],
    learningOutcomes: [
      "Identify viable rural enterprise opportunities",
      "Prepare a fundable business plan",
      "Apply for government schemes and cooperative credit",
      "Set up basic business operations and accounts",
    ],
    documentsRequired: ["Aadhaar Card", "Education Certificate", "Cooperative Membership Proof", "Passport Photo"],
    fee: 2000,
    isFree: false,
    status: "active",
    featured: false,
    recommended: false,
    applicationCount: 18,
    rating: 4.4,
    tags: ["entrepreneurship", "rural", "business", "Gujarat"],
  },
  {
    id: "prog-cold-chain-009",
    title: "Dairy Cold Chain Operations & Milk Testing",
    shortDescription: "Technical operations programme focused on modern dairy cold chain management and advanced milk quality testing.",
    fullDescription: "An intensive technical training covering Bulk Milk Cooler (BMC) operations, automatic milk collection unit management, advanced milk quality parameters, and integrated cold chain tracking systems. Includes hands-on practical at NDRI demonstration dairy.",
    type: "training",
    category: "Dairy & Agriculture",
    institution: "NDRI Karnal",
    institutionId: "inst-8",
    location: "Karnal, Haryana",
    state: "Haryana",
    district: "Karnal",
    mode: "On-Campus",
    language: ["Hindi", "English"],
    startDate: "2026-11-10",
    endDate: "2026-12-05",
    duration: 4,
    durationUnit: "weeks",
    registrationDeadline: "2026-10-28",
    totalSeats: 25,
    availableSeats: 9,
    level: "Intermediate",
    certificateType: "Certificate",
    skills: ["Cold Chain Management", "BMC Operations", "Milk Quality Testing", "AMCU Operations", "HACCP"],
    eligibility: ["10th pass minimum", "Dairy cooperative employee", "Age 18-40"],
    eligibilityRules: baseEligibilityRules,
    hostelAvailable: true,
    mealAvailable: true,
    transportAvailable: true,
    trainerIds: ["trainer-3"],
    curriculum: [
      { week: 1, title: "Cold Chain Fundamentals", topics: ["Refrigeration Basics", "BMC Types", "Temperature Monitoring", "Energy Management"], hours: 30 },
      { week: 2, title: "AMCU Operations", topics: ["Electronic Milk Tester", "AMCU Configuration", "Data Entry", "Troubleshooting"], hours: 30 },
      { week: 3, title: "Advanced Quality Testing", topics: ["Adulteration Tests", "Antibiotic Residue", "Microbial Testing", "HACCP Implementation"], hours: 30 },
      { week: 4, title: "Integrated Systems", topics: ["Cold Chain Tracking", "ERP Integration", "Reporting", "Assessment"], hours: 30 },
    ],
    learningOutcomes: [
      "Operate and maintain dairy BMC and AMCU equipment",
      "Conduct advanced milk quality tests and interpret results",
      "Implement HACCP-based quality management systems",
      "Manage integrated cold chain tracking and reporting",
    ],
    documentsRequired: ["Aadhaar Card", "Education Certificate", "Employment Letter", "Cooperative Membership Proof", "Passport Photo", "Medical Fitness Certificate"],
    fee: 5500,
    isFree: false,
    status: "active",
    featured: false,
    recommended: true,
    applicationCount: 16,
    rating: 4.7,
    tags: ["dairy", "cold chain", "BMC", "quality", "technical"],
  },
  {
    id: "prog-coop-law-010",
    title: "Cooperative Law & Compliance",
    shortDescription: "Intensive legal training on cooperative law, MSCS Act, state cooperative laws and regulatory compliance requirements.",
    fullDescription: "A focused legal programme covering the Multi-State Cooperative Societies Act 2002, state-level cooperative acts, case law, compliance calendar, and practical guidance on handling disputes, elections and registrar proceedings. Suitable for cooperative secretaries, officers and board members.",
    type: "training",
    category: "Governance & Compliance",
    institution: "ICM Bhopal",
    institutionId: "inst-4",
    location: "Bhopal, Madhya Pradesh",
    state: "Madhya Pradesh",
    district: "Bhopal",
    mode: "Hybrid",
    language: ["Hindi", "English"],
    startDate: "2026-12-15",
    endDate: "2026-12-28",
    duration: 2,
    durationUnit: "weeks",
    registrationDeadline: "2026-11-30",
    totalSeats: 50,
    availableSeats: 28,
    level: "Intermediate",
    certificateType: "Certificate",
    skills: ["Cooperative Law", "MSCS Act", "Regulatory Compliance", "Legal Documentation", "Dispute Resolution"],
    eligibility: ["Graduate minimum", "Cooperative member or officer"],
    eligibilityRules: [
      { field: "education", label: "Minimum Education", operator: "in", value: ["Graduate", "Post-Graduate"], description: "Graduate required" },
      ...baseEligibilityRules.slice(1),
    ],
    hostelAvailable: false,
    mealAvailable: false,
    transportAvailable: false,
    trainerIds: ["trainer-5", "trainer-1"],
    curriculum: [
      { week: 1, title: "Legal Framework", topics: ["MSCS Act 2002", "State Acts", "Model Byelaws", "AGM Requirements", "Elections"], hours: 40 },
      { week: 2, title: "Compliance & Disputes", topics: ["Compliance Calendar", "Dispute Resolution", "Arbitration", "Registrar Proceedings", "Mock Court"], hours: 40 },
    ],
    learningOutcomes: [
      "Navigate MSCS Act and applicable state cooperative law",
      "Maintain compliance with all statutory requirements",
      "Resolve member disputes through appropriate channels",
      "Manage cooperative elections and governance processes",
    ],
    documentsRequired: ["Aadhaar Card", "Education Certificate", "Cooperative Membership Proof", "Passport Photo"],
    fee: 2000,
    isFree: false,
    status: "active",
    featured: false,
    recommended: false,
    applicationCount: 22,
    rating: 4.5,
    tags: ["law", "compliance", "MSCS", "governance"],
  },
  {
    id: "prog-coop-leadership-011",
    title: "Cooperative Leadership & Governance",
    shortDescription: "Executive development programme for senior cooperative leaders covering strategy, leadership and organizational excellence.",
    fullDescription: "Designed for senior cooperative leaders, board members and CEOs, this executive programme covers strategic planning, leadership development, change management and organisational excellence in cooperative contexts. Features guest lectures from industry leaders and peer learning.",
    type: "training",
    category: "Leadership",
    institution: "VAMNICOM Pune",
    institutionId: "inst-1",
    location: "Pune, Maharashtra",
    state: "Maharashtra",
    district: "Pune",
    mode: "On-Campus",
    language: ["English", "Hindi"],
    startDate: "2027-01-10",
    endDate: "2027-01-31",
    duration: 3,
    durationUnit: "weeks",
    registrationDeadline: "2026-12-15",
    totalSeats: 25,
    availableSeats: 20,
    level: "Advanced",
    certificateType: "Diploma",
    skills: ["Strategic Planning", "Leadership", "Change Management", "Cooperative Excellence", "Stakeholder Management"],
    eligibility: ["Graduate minimum", "5+ years cooperative experience", "Senior officer or board member"],
    eligibilityRules: [
      { field: "education", label: "Minimum Education", operator: "in", value: ["Graduate", "Post-Graduate"], description: "Graduate required" },
      { field: "experience", label: "Experience", operator: "gte", value: 5, description: "5+ years in cooperative sector" },
      { field: "cooperativeMembership", label: "Cooperative Position", operator: "exists", value: "yes", description: "Senior position required" },
    ],
    hostelAvailable: true,
    mealAvailable: true,
    transportAvailable: false,
    trainerIds: ["trainer-5"],
    curriculum: [
      { week: 1, title: "Strategic Leadership", topics: ["Strategic Thinking", "Vision & Mission", "Cooperative Identity", "Leadership Styles"], hours: 35 },
      { week: 2, title: "Governance Excellence", topics: ["Board Effectiveness", "Member Engagement", "Performance Management", "Succession Planning"], hours: 35 },
      { week: 3, title: "Change & Innovation", topics: ["Digital Transformation", "Change Management", "Innovation Framework", "Case Studies"], hours: 35 },
    ],
    learningOutcomes: [
      "Develop and communicate a compelling cooperative vision",
      "Lead high-performing boards and governance structures",
      "Manage organisational change in cooperative context",
      "Drive innovation and digital transformation",
    ],
    documentsRequired: ["Aadhaar Card", "Education Certificate", "Experience Certificate", "Cooperative Membership Proof", "Passport Photo"],
    fee: 8000,
    isFree: false,
    status: "upcoming",
    featured: true,
    recommended: false,
    applicationCount: 5,
    rating: 4.9,
    tags: ["leadership", "executive", "advanced", "diploma"],
  },
  {
    id: "prog-digital-payments-012",
    title: "Digital Payments for PACS",
    shortDescription: "Practical training on implementing and managing digital payment systems in Primary Agricultural Credit Societies.",
    fullDescription: "A hands-on programme focused on deploying UPI, NEFT, RTGS and government-linked payment systems within PACS. Covers BC agent operations, AePS, PMJJBY and PMSBY linking, and common technical troubleshooting scenarios.",
    type: "digital-literacy",
    category: "Digital Literacy",
    institution: "RICM Pune",
    institutionId: "inst-2",
    location: "Pune, Maharashtra",
    state: "Maharashtra",
    district: "Pune",
    mode: "Hybrid",
    language: ["Marathi", "Hindi", "English"],
    startDate: "2026-11-18",
    endDate: "2026-11-29",
    duration: 2,
    durationUnit: "weeks",
    registrationDeadline: "2026-11-05",
    totalSeats: 60,
    availableSeats: 42,
    level: "Beginner",
    certificateType: "Certificate",
    skills: ["UPI", "AePS", "BC Agent Operations", "Digital Payments", "PMJDY"],
    eligibility: ["10th pass minimum", "PACS employee or officer"],
    eligibilityRules: baseEligibilityRules,
    hostelAvailable: false,
    mealAvailable: true,
    transportAvailable: false,
    trainerIds: ["trainer-4"],
    curriculum: [
      { week: 1, title: "Digital Payment Systems", topics: ["UPI Ecosystem", "BHIM", "Bank Linkage", "AePS Operations"], hours: 40 },
      { week: 2, title: "PACS Implementation", topics: ["BC Agent Setup", "Government Schemes", "Troubleshooting", "Customer Support"], hours: 40 },
    ],
    learningOutcomes: [
      "Set up and operate AePS and UPI for PACS members",
      "Function as a Business Correspondent agent",
      "Handle digital payment queries and complaints",
      "Maintain digital transaction records",
    ],
    documentsRequired: ["Aadhaar Card", "Education Certificate", "PACS Employment Letter", "Passport Photo"],
    fee: 1200,
    isFree: false,
    status: "active",
    featured: false,
    recommended: false,
    applicationCount: 18,
    rating: 4.3,
    tags: ["digital", "payments", "PACS", "UPI", "AePS"],
  },
  {
    id: "prog-rural-credit-013",
    title: "Rural Credit & KCC Operations",
    shortDescription: "Comprehensive training on rural credit products, Kisan Credit Card operations and cooperative lending best practices.",
    fullDescription: "A specialized programme for cooperative credit officers covering the full spectrum of rural credit — from KCC issuance and limit-setting to NPA management, recovery strategies and RBI guidelines for cooperative banks. Includes case studies from successful and distressed PACS.",
    type: "training",
    category: "Finance & Accounting",
    institution: "RICM Lucknow",
    institutionId: "inst-3",
    location: "Lucknow, Uttar Pradesh",
    state: "Uttar Pradesh",
    district: "Lucknow",
    mode: "On-Campus",
    language: ["Hindi", "English"],
    startDate: "2026-11-22",
    endDate: "2026-12-13",
    duration: 3,
    durationUnit: "weeks",
    registrationDeadline: "2026-11-08",
    totalSeats: 40,
    availableSeats: 16,
    level: "Intermediate",
    certificateType: "Certificate",
    skills: ["KCC Operations", "Rural Credit", "NPA Management", "Recovery", "RBI Guidelines", "Credit Appraisal"],
    eligibility: ["Graduate minimum", "Cooperative credit experience preferred"],
    eligibilityRules: [
      { field: "education", label: "Minimum Education", operator: "in", value: ["Graduate", "Post-Graduate"], description: "Graduate required" },
      ...baseEligibilityRules.slice(1),
    ],
    hostelAvailable: true,
    mealAvailable: true,
    transportAvailable: false,
    trainerIds: ["trainer-6"],
    curriculum: [
      { week: 1, title: "KCC & Rural Credit", topics: ["KCC Scheme", "Limit Setting", "Crop Loans", "Investment Credit"], hours: 35 },
      { week: 2, title: "Credit Management", topics: ["Appraisal", "Documentation", "Disbursement", "Monitoring"], hours: 35 },
      { week: 3, title: "NPA & Recovery", topics: ["NPA Classification", "Recovery Strategies", "Legal Options", "One-Time Settlement"], hours: 35 },
    ],
    learningOutcomes: [
      "Process Kisan Credit Card applications accurately",
      "Conduct credit appraisal for rural borrowers",
      "Manage NPA portfolio and implement recovery strategies",
      "Maintain compliance with RBI guidelines for cooperative credit",
    ],
    documentsRequired: ["Aadhaar Card", "Education Certificate", "Employment Letter", "Cooperative Membership Proof", "Passport Photo"],
    fee: 3500,
    isFree: false,
    status: "active",
    featured: false,
    recommended: false,
    applicationCount: 24,
    rating: 4.6,
    tags: ["credit", "KCC", "rural", "finance", "NPA"],
  },
  {
    id: "prog-marketing-ecomm-014",
    title: "Cooperative Marketing & E-Commerce",
    shortDescription: "Digital marketing and e-commerce programme for cooperative businesses to expand market reach online.",
    fullDescription: "A practical programme covering digital marketing strategies, e-commerce platform setup, online product listing, logistics management and customer relationship management tailored for cooperative enterprises. Includes live workshops on Amazon, Flipkart, and ONDC platforms.",
    type: "skill-development",
    category: "Marketing & Commerce",
    institution: "ICM Hyderabad",
    institutionId: "inst-6",
    location: "Hyderabad, Telangana",
    state: "Telangana",
    district: "Hyderabad",
    mode: "Online",
    language: ["Telugu", "Hindi", "English"],
    startDate: "2026-11-15",
    endDate: "2026-12-06",
    duration: 3,
    durationUnit: "weeks",
    registrationDeadline: "2026-11-01",
    totalSeats: 80,
    availableSeats: 45,
    level: "Beginner",
    certificateType: "Certificate",
    skills: ["Digital Marketing", "E-Commerce", "Social Media", "ONDC", "Online Logistics"],
    eligibility: ["10th pass minimum", "Cooperative member or employee", "Basic smartphone usage"],
    eligibilityRules: baseEligibilityRules,
    hostelAvailable: false,
    mealAvailable: false,
    transportAvailable: false,
    trainerIds: ["trainer-7"],
    curriculum: [
      { week: 1, title: "Digital Marketing", topics: ["Social Media Marketing", "Content Creation", "WhatsApp Business", "Local SEO"], hours: 30 },
      { week: 2, title: "E-Commerce Platforms", topics: ["Amazon Seller", "Flipkart", "ONDC Onboarding", "Product Listing"], hours: 30 },
      { week: 3, title: "Operations & Scale", topics: ["Order Management", "Logistics", "Customer Service", "Performance Analytics"], hours: 30 },
    ],
    learningOutcomes: [
      "Create and manage social media presence for cooperative products",
      "List and sell products on major e-commerce platforms",
      "Manage online orders and customer relationships",
      "Analyse digital marketing performance",
    ],
    documentsRequired: ["Aadhaar Card", "Cooperative Membership Proof", "Passport Photo"],
    fee: 1800,
    isFree: false,
    status: "active",
    featured: false,
    recommended: false,
    applicationCount: 45,
    rating: 4.4,
    tags: ["marketing", "e-commerce", "online", "cooperative"],
  },
  {
    id: "prog-data-literacy-015",
    title: "Data Literacy for Cooperative Institutions",
    shortDescription: "Build data analysis and reporting skills for cooperative managers using accessible tools like Excel and Google Sheets.",
    fullDescription: "A practical data literacy programme designed to help cooperative institution staff move from manual report filing to data-driven decision making. Covers Excel/Google Sheets, basic data visualisation, dashboard creation, and using NCCT's reporting portal effectively.",
    type: "digital-literacy",
    category: "Digital Literacy",
    institution: "RICM Pune",
    institutionId: "inst-2",
    location: "Pune, Maharashtra",
    state: "Maharashtra",
    district: "Pune",
    mode: "Hybrid",
    language: ["English", "Marathi", "Hindi"],
    startDate: "2026-12-01",
    endDate: "2026-12-14",
    duration: 2,
    durationUnit: "weeks",
    registrationDeadline: "2026-11-18",
    totalSeats: 45,
    availableSeats: 24,
    level: "Beginner",
    certificateType: "Certificate",
    skills: ["Excel", "Data Analysis", "Data Visualization", "Dashboard Creation", "NCCT Reporting"],
    eligibility: ["12th pass minimum", "Cooperative institution staff"],
    eligibilityRules: [
      { field: "education", label: "Minimum Education", operator: "in", value: ["12th Pass", "Graduate", "Post-Graduate"], description: "12th standard minimum" },
      ...baseEligibilityRules.slice(1),
    ],
    hostelAvailable: false,
    mealAvailable: false,
    transportAvailable: false,
    trainerIds: ["trainer-4"],
    curriculum: [
      { week: 1, title: "Data Fundamentals", topics: ["Excel Basics", "Data Entry", "Formulas", "Sorting & Filtering"], hours: 40 },
      { week: 2, title: "Analysis & Reporting", topics: ["Pivot Tables", "Charts", "Dashboards", "NCCT Portal Reports"], hours: 40 },
    ],
    learningOutcomes: [
      "Collect and organise data systematically in Excel",
      "Create meaningful charts and pivot tables",
      "Build simple dashboards for cooperative management",
      "Submit reports through NCCT digital portal",
    ],
    documentsRequired: ["Aadhaar Card", "Education Certificate", "Employment Letter", "Passport Photo"],
    fee: 1500,
    isFree: false,
    status: "active",
    featured: false,
    recommended: false,
    applicationCount: 21,
    rating: 4.3,
    tags: ["data", "Excel", "analysis", "digital"],
  },
  {
    id: "prog-women-coop-016",
    title: "Women-led Cooperative Enterprise",
    shortDescription: "Empowerment programme for women cooperative leaders covering enterprise management, leadership and financial inclusion.",
    fullDescription: "A comprehensive women's empowerment programme that covers legal rights, enterprise development, cooperative governance, leadership skills and financial inclusion. Features mentoring by successful women cooperative leaders from across India and peer networking sessions.",
    type: "skill-development",
    category: "Enterprise Development",
    institution: "VAMNICOM Pune",
    institutionId: "inst-1",
    location: "Pune, Maharashtra",
    state: "Maharashtra",
    district: "Pune",
    mode: "On-Campus",
    language: ["Marathi", "Hindi", "English"],
    startDate: "2026-12-08",
    endDate: "2026-12-21",
    duration: 2,
    durationUnit: "weeks",
    registrationDeadline: "2026-11-24",
    totalSeats: 50,
    availableSeats: 32,
    level: "Beginner",
    certificateType: "Certificate",
    skills: ["Leadership", "Enterprise Management", "Financial Inclusion", "Women's Rights", "Cooperative Governance"],
    eligibility: ["8th pass minimum", "Women cooperative member", "SHG or cooperative leader preferred"],
    eligibilityRules: [
      { field: "education", label: "Minimum Education", operator: "in", value: ["8th Pass", "10th Pass", "12th Pass", "Graduate", "Post-Graduate"], description: "8th standard minimum" },
      { field: "gender", label: "Women Only", operator: "eq", value: "female", description: "Programme is designed for women participants" },
      { field: "cooperativeMembership", label: "Cooperative Member", operator: "exists", value: "yes", description: "Must be a cooperative or SHG member" },
    ],
    hostelAvailable: true,
    mealAvailable: true,
    transportAvailable: false,
    trainerIds: ["trainer-8"],
    curriculum: [
      { week: 1, title: "Leadership & Rights", topics: ["Women's Legal Rights", "Leadership Skills", "Communication", "Decision Making"], hours: 40 },
      { week: 2, title: "Enterprise & Finance", topics: ["Business Setup", "Credit Access", "Market Linkage", "Mentoring Sessions"], hours: 40 },
    ],
    learningOutcomes: [
      "Lead cooperative boards and SHG federations confidently",
      "Access credit and government schemes for women enterprises",
      "Build and manage a small cooperative business",
      "Network effectively with women cooperative leaders",
    ],
    documentsRequired: ["Aadhaar Card", "SHG/Cooperative Membership Certificate", "Passport Photo"],
    fee: 0,
    isFree: true,
    status: "active",
    featured: false,
    recommended: false,
    applicationCount: 18,
    rating: 4.6,
    tags: ["women", "enterprise", "leadership", "free"],
  },
  {
    id: "prog-supply-chain-017",
    title: "Rural Supply Chain Management",
    shortDescription: "End-to-end supply chain management training for cooperative managers in agriculture and agri-processing sectors.",
    fullDescription: "A comprehensive supply chain programme covering procurement, warehousing, logistics, quality control and distribution management in rural cooperative contexts. Includes field visits to cooperative warehouses and APMC markets.",
    type: "training",
    category: "Operations & Logistics",
    institution: "ICM Hyderabad",
    institutionId: "inst-6",
    location: "Hyderabad, Telangana",
    state: "Telangana",
    district: "Hyderabad",
    mode: "On-Campus",
    language: ["Telugu", "English", "Hindi"],
    startDate: "2026-11-28",
    endDate: "2026-12-19",
    duration: 3,
    durationUnit: "weeks",
    registrationDeadline: "2026-11-14",
    totalSeats: 35,
    availableSeats: 18,
    level: "Intermediate",
    certificateType: "Certificate",
    skills: ["Supply Chain", "Procurement", "Warehousing", "Logistics", "Quality Control", "APMC"],
    eligibility: ["Graduate minimum", "Cooperative employment", "Operations background preferred"],
    eligibilityRules: [
      { field: "education", label: "Minimum Education", operator: "in", value: ["Graduate", "Post-Graduate"], description: "Graduate required" },
      ...baseEligibilityRules.slice(1),
    ],
    hostelAvailable: false,
    mealAvailable: true,
    transportAvailable: false,
    trainerIds: ["trainer-7"],
    curriculum: [
      { week: 1, title: "Procurement & Sourcing", topics: ["Member Procurement", "Quality Standards", "Price Discovery", "Contract Farming"], hours: 35 },
      { week: 2, title: "Warehousing & Logistics", topics: ["Warehouse Management", "Cold Storage", "Transport Planning", "Route Optimization"], hours: 35 },
      { week: 3, title: "Market Integration", topics: ["APMC Operations", "Agri-Marketing", "Export Basics", "E-NAM"], hours: 35 },
    ],
    learningOutcomes: [
      "Design and manage cooperative supply chains efficiently",
      "Select suppliers and manage procurement processes",
      "Operate warehouse and logistics systems",
      "Integrate with APMC and online agricultural markets",
    ],
    documentsRequired: ["Aadhaar Card", "Education Certificate", "Employment Letter", "Cooperative Membership Proof", "Passport Photo"],
    fee: 4000,
    isFree: false,
    status: "active",
    featured: false,
    recommended: false,
    applicationCount: 17,
    rating: 4.4,
    tags: ["supply chain", "logistics", "operations", "APMC"],
  },
  {
    id: "prog-hr-member-018",
    title: "Cooperative HR & Member Relations",
    shortDescription: "Human resource management and member engagement skills for cooperative administrators and HR officers.",
    fullDescription: "A practical HR programme covering recruitment, performance management, conflict resolution, member grievance handling and cooperative industrial relations. Includes case studies from cooperatives with strong HR practices across India.",
    type: "training",
    category: "Human Resources",
    institution: "ICM Bhopal",
    institutionId: "inst-4",
    location: "Bhopal, Madhya Pradesh",
    state: "Madhya Pradesh",
    district: "Bhopal",
    mode: "On-Campus",
    language: ["Hindi", "English"],
    startDate: "2027-01-05",
    endDate: "2027-01-23",
    duration: 3,
    durationUnit: "weeks",
    registrationDeadline: "2026-12-20",
    totalSeats: 40,
    availableSeats: 35,
    level: "Intermediate",
    certificateType: "Certificate",
    skills: ["HR Management", "Member Relations", "Conflict Resolution", "Performance Management", "Industrial Relations"],
    eligibility: ["Graduate minimum", "Cooperative HR or admin role", "1+ year experience"],
    eligibilityRules: [
      { field: "education", label: "Minimum Education", operator: "in", value: ["Graduate", "Post-Graduate"], description: "Graduate required" },
      ...baseEligibilityRules.slice(1),
    ],
    hostelAvailable: true,
    mealAvailable: true,
    transportAvailable: false,
    trainerIds: ["trainer-5", "trainer-8"],
    curriculum: [
      { week: 1, title: "HR Fundamentals", topics: ["Recruitment", "Onboarding", "Service Rules", "Payroll Basics"], hours: 35 },
      { week: 2, title: "Performance & Development", topics: ["Performance Appraisal", "Training Need Analysis", "Career Planning"], hours: 35 },
      { week: 3, title: "Member Relations", topics: ["Grievance Handling", "Disciplinary Procedures", "Conflict Resolution", "Case Studies"], hours: 35 },
    ],
    learningOutcomes: [
      "Manage cooperative recruitment and onboarding",
      "Conduct fair performance appraisals",
      "Handle member grievances professionally",
      "Manage industrial relations in cooperative context",
    ],
    documentsRequired: ["Aadhaar Card", "Education Certificate", "Employment Letter", "Cooperative Membership Proof", "Passport Photo"],
    fee: 3000,
    isFree: false,
    status: "upcoming",
    featured: false,
    recommended: false,
    applicationCount: 5,
    rating: 4.3,
    tags: ["HR", "management", "member relations", "cooperative"],
  },
  {
    id: "prog-pacs-bookkeeping-019",
    title: "Advanced PACS Bookkeeping",
    shortDescription: "Advanced bookkeeping certification programme for PACS staff covering complex financial transactions and NAFCOB compliance.",
    fullDescription: "Building on basic bookkeeping skills, this advanced programme covers complex journal entries, subsidiary registers, NAFCOB-compliant annual accounts preparation, inter-cooperative transactions and preparation of audit-ready financial statements. Includes a graded practical assessment.",
    type: "training",
    category: "Finance & Accounting",
    institution: "RICM Pune",
    institutionId: "inst-2",
    location: "Pune, Maharashtra",
    state: "Maharashtra",
    district: "Pune",
    mode: "On-Campus",
    language: ["Marathi", "Hindi", "English"],
    startDate: "2026-11-17",
    endDate: "2026-12-05",
    duration: 3,
    durationUnit: "weeks",
    registrationDeadline: "2026-11-03",
    totalSeats: 30,
    availableSeats: 11,
    level: "Advanced",
    certificateType: "Certificate",
    skills: ["Advanced Bookkeeping", "NAFCOB Accounts", "Subsidiary Registers", "Annual Accounts", "Audit Preparation"],
    eligibility: ["Graduate minimum", "Basic bookkeeping knowledge", "PACS employee"],
    eligibilityRules: [
      { field: "education", label: "Minimum Education", operator: "in", value: ["Graduate", "Post-Graduate"], description: "Graduate required" },
      { field: "experience", label: "Bookkeeping Experience", operator: "gte", value: 1, description: "1 year bookkeeping experience" },
      ...baseEligibilityRules.slice(1, 2),
    ],
    hostelAvailable: false,
    mealAvailable: true,
    transportAvailable: false,
    trainerIds: ["trainer-2"],
    curriculum: [
      { week: 1, title: "Complex Transactions", topics: ["Complex Journals", "Subsidiary Registers", "Inter-PACS Transactions", "Provisions"], hours: 35 },
      { week: 2, title: "NAFCOB Compliance", topics: ["NAFCOB Chart of Accounts", "Annual Accounts Format", "Profit Distribution", "Reserve Funds"], hours: 35 },
      { week: 3, title: "Audit Preparation", topics: ["Audit Trail", "Document Filing", "Auditor Queries", "Assessment"], hours: 35 },
    ],
    learningOutcomes: [
      "Handle complex financial transactions in PACS accounts",
      "Prepare NAFCOB-compliant annual financial statements",
      "Maintain all required subsidiary registers",
      "Prepare audit-ready documentation packages",
    ],
    documentsRequired: ["Aadhaar Card", "Education Certificate", "Employment Letter", "Bookkeeping Course Certificate", "Cooperative Membership Proof", "Passport Photo"],
    fee: 3500,
    isFree: false,
    status: "active",
    featured: false,
    recommended: false,
    applicationCount: 19,
    rating: 4.7,
    tags: ["bookkeeping", "advanced", "NAFCOB", "PACS", "accounting"],
  },
  {
    id: "prog-milk-testing-020",
    title: "Milk Testing & Quality Assurance",
    shortDescription: "Practical certification programme for dairy cooperative quality control staff in milk testing and quality assurance.",
    fullDescription: "A hands-on programme for dairy cooperative quality control personnel covering milk composition testing, adulteration detection, microbiological testing, equipment calibration and maintenance, and quality management systems. Conducted at a fully equipped dairy laboratory.",
    type: "skill-development",
    category: "Dairy & Agriculture",
    institution: "NDRI Karnal",
    institutionId: "inst-8",
    location: "Karnal, Haryana",
    state: "Haryana",
    district: "Karnal",
    mode: "On-Campus",
    language: ["Hindi", "English"],
    startDate: "2026-12-10",
    endDate: "2026-12-30",
    duration: 3,
    durationUnit: "weeks",
    registrationDeadline: "2026-11-25",
    totalSeats: 20,
    availableSeats: 13,
    level: "Intermediate",
    certificateType: "Certificate",
    skills: ["Milk Testing", "Quality Assurance", "Lab Operations", "Adulteration Detection", "Equipment Calibration"],
    eligibility: ["12th pass (Science preferred)", "Dairy cooperative employee"],
    eligibilityRules: [
      { field: "education", label: "Minimum Education", operator: "in", value: ["12th Pass", "Graduate", "Post-Graduate"], description: "12th standard (Science preferred)" },
      ...baseEligibilityRules.slice(1),
    ],
    hostelAvailable: true,
    mealAvailable: true,
    transportAvailable: true,
    trainerIds: ["trainer-3"],
    curriculum: [
      { week: 1, title: "Milk Composition Testing", topics: ["Fat Testing", "SNF Testing", "Lactometer", "Gerber Method"], hours: 35 },
      { week: 2, title: "Adulteration & Microbiology", topics: ["MBRT Test", "Adulteration Screening", "Antibiotic Residue", "FSSAI Standards"], hours: 35 },
      { week: 3, title: "Quality Systems & Equipment", topics: ["Calibration", "GMP Principles", "Documentation", "Assessment"], hours: 35 },
    ],
    learningOutcomes: [
      "Conduct standard milk quality tests accurately",
      "Detect common adulterants in milk samples",
      "Implement FSSAI-compliant quality management",
      "Maintain and calibrate dairy testing equipment",
    ],
    documentsRequired: ["Aadhaar Card", "Education Certificate", "Employment Letter", "Medical Fitness Certificate", "Passport Photo"],
    fee: 4500,
    isFree: false,
    status: "active",
    featured: false,
    recommended: false,
    applicationCount: 7,
    rating: 4.6,
    tags: ["dairy", "quality", "testing", "laboratory"],
  },
  {
    id: "prog-agri-value-021",
    title: "Agri Value Chain Development",
    shortDescription: "Strategic programme on developing and managing agricultural value chains through cooperatives.",
    fullDescription: "This programme equips cooperative managers with tools to develop effective agricultural value chains — from input supply and primary processing to branding, retail and export. Includes practical modules on FPO management, agri-processing units and cooperative trading houses.",
    type: "training",
    category: "Operations & Logistics",
    institution: "ICM Anand",
    institutionId: "inst-7",
    location: "Anand, Gujarat",
    state: "Gujarat",
    district: "Anand",
    mode: "Hybrid",
    language: ["Gujarati", "Hindi", "English"],
    startDate: "2027-01-15",
    endDate: "2027-02-05",
    duration: 3,
    durationUnit: "weeks",
    registrationDeadline: "2027-01-01",
    totalSeats: 35,
    availableSeats: 30,
    level: "Advanced",
    certificateType: "Diploma",
    skills: ["Value Chain Analysis", "FPO Management", "Agri-Processing", "Export Basics", "Cooperative Trading"],
    eligibility: ["Graduate minimum", "Cooperative officer", "3+ years experience"],
    eligibilityRules: [
      { field: "education", label: "Minimum Education", operator: "in", value: ["Graduate", "Post-Graduate"], description: "Graduate required" },
      { field: "experience", label: "Experience", operator: "gte", value: 3, description: "3 years cooperative sector experience" },
      ...baseEligibilityRules.slice(1, 2),
    ],
    hostelAvailable: false,
    mealAvailable: false,
    transportAvailable: false,
    trainerIds: ["trainer-7", "trainer-5"],
    curriculum: [
      { week: 1, title: "Value Chain Analysis", topics: ["Mapping Value Chains", "Actors & Relationships", "Cost & Margin Analysis", "Bottlenecks"], hours: 35 },
      { week: 2, title: "Operations & Processing", topics: ["Processing Unit Setup", "Quality Systems", "Packaging", "Branding"], hours: 35 },
      { week: 3, title: "Market Integration", topics: ["Retail Linkages", "Export Procedures", "e-NAM", "FPO Success Stories"], hours: 35 },
    ],
    learningOutcomes: [
      "Analyse and map cooperative agricultural value chains",
      "Design and implement agri-processing unit operations",
      "Integrate cooperatives with retail and export markets",
      "Manage FPO operations effectively",
    ],
    documentsRequired: ["Aadhaar Card", "Education Certificate", "Experience Certificate", "Cooperative Membership Proof", "Passport Photo"],
    fee: 7000,
    isFree: false,
    status: "upcoming",
    featured: false,
    recommended: false,
    applicationCount: 5,
    rating: 4.8,
    tags: ["value chain", "agri", "FPO", "export", "diploma"],
  },
];

export const MOCK_EXAMS: CertificationExam[] = [
  {
    id: "exam-coop-acc-001",
    name: "Cooperative Accounting Certification",
    shortName: "CAC",
    issuer: "NCCT",
    description: "National-level certification validating competency in cooperative accounting, bookkeeping and financial reporting standards.",
    eligibility: ["12th pass minimum", "Cooperative employment", "Basic bookkeeping knowledge"],
    eligibilityRules: [
      { field: "education", label: "Minimum Education", operator: "in", value: ["12th Pass", "Graduate", "Post-Graduate"], description: "12th standard minimum" },
      ...baseEligibilityRules.slice(1),
    ],
    registrationDeadline: "2026-10-31",
    examDate: "2026-11-20",
    duration: 180,
    durationUnit: "minutes",
    mode: "On-Campus",
    availableSlots: 200,
    filledSlots: 148,
    fee: 500,
    isFree: false,
    certificateType: "Certificate",
    skillsAssessed: ["Double Entry Bookkeeping", "PACS Accounting", "Financial Statements", "Audit Basics"],
    language: ["English", "Hindi", "Marathi"],
    status: "open",
    passingScore: 60,
    syllabus: ["Accounting Principles", "PACS Accounts", "Annual Accounts Preparation", "Audit & Compliance"],
  },
  {
    id: "exam-pacs-digital-002",
    name: "PACS Digital Operations Certification",
    shortName: "PDOC",
    issuer: "NCCT",
    description: "Certification for PACS staff demonstrating proficiency in digital operations, UPI, AePS and cooperative management software.",
    eligibility: ["10th pass minimum", "PACS employee"],
    eligibilityRules: baseEligibilityRules,
    registrationDeadline: "2026-11-10",
    examDate: "2026-11-28",
    duration: 120,
    durationUnit: "minutes",
    mode: "Online",
    availableSlots: 500,
    filledSlots: 312,
    fee: 300,
    isFree: false,
    certificateType: "Certificate",
    skillsAssessed: ["Digital Payments", "UPI/AePS", "Cooperative Software", "Online Services"],
    language: ["English", "Hindi", "Marathi", "Gujarati"],
    status: "open",
    passingScore: 65,
    syllabus: ["Digital Payments Ecosystem", "AePS Operations", "Cooperative Management Software", "Data Security"],
  },
  {
    id: "exam-dairy-ops-003",
    name: "Dairy Operations Certification",
    shortName: "DOC",
    issuer: "NDRI / NCCT",
    description: "Jointly certified examination validating comprehensive knowledge of dairy cooperative operations, milk testing and quality management.",
    eligibility: ["10th pass minimum", "Dairy cooperative employee", "6 months experience"],
    eligibilityRules: baseEligibilityRules,
    registrationDeadline: "2026-11-15",
    examDate: "2026-12-05",
    duration: 180,
    durationUnit: "minutes",
    mode: "On-Campus",
    availableSlots: 150,
    filledSlots: 89,
    fee: 600,
    isFree: false,
    certificateType: "Certificate",
    skillsAssessed: ["Milk Testing", "Cold Chain", "BMC Operations", "Quality Standards", "Cooperative Management"],
    language: ["Hindi", "English"],
    status: "open",
    passingScore: 60,
    syllabus: ["Milk Composition & Testing", "Cold Chain Operations", "Quality Management", "Cooperative Finance"],
  },
  {
    id: "exam-coop-governance-004",
    name: "Cooperative Governance Certification",
    shortName: "CGC",
    issuer: "NCCT",
    description: "Advanced certification for cooperative officers and board members covering governance frameworks, legal compliance and leadership.",
    eligibility: ["Graduate minimum", "Cooperative officer position", "2+ years experience"],
    eligibilityRules: [
      { field: "education", label: "Minimum Education", operator: "in", value: ["Graduate", "Post-Graduate"], description: "Graduate required" },
      { field: "experience", label: "Experience", operator: "gte", value: 2, description: "2 years cooperative experience" },
      ...baseEligibilityRules.slice(1, 2),
    ],
    registrationDeadline: "2026-12-01",
    examDate: "2026-12-20",
    duration: 240,
    durationUnit: "minutes",
    mode: "On-Campus",
    availableSlots: 100,
    filledSlots: 67,
    fee: 800,
    isFree: false,
    certificateType: "Diploma",
    skillsAssessed: ["Cooperative Law", "Governance", "Audit", "Strategic Management", "Member Relations"],
    language: ["English", "Hindi"],
    status: "open",
    passingScore: 70,
    syllabus: ["Legal Framework", "Governance Structures", "Audit & Compliance", "Cooperative Strategy"],
  },
  {
    id: "exam-rural-ent-005",
    name: "Rural Entrepreneurship Certification",
    shortName: "REC",
    issuer: "NCCT",
    description: "Certification recognising competency in rural enterprise development, business planning and access to cooperative finance.",
    eligibility: ["10th pass minimum", "Cooperative member or SHG member"],
    eligibilityRules: baseEligibilityRules,
    registrationDeadline: "2026-11-20",
    examDate: "2026-12-10",
    duration: 120,
    durationUnit: "minutes",
    mode: "Online",
    availableSlots: 300,
    filledSlots: 187,
    fee: 250,
    isFree: false,
    certificateType: "Certificate",
    skillsAssessed: ["Business Planning", "Financial Management", "Market Analysis", "Government Schemes"],
    language: ["Hindi", "English", "Marathi", "Gujarati", "Telugu"],
    status: "open",
    passingScore: 55,
    syllabus: ["Rural Enterprise Concepts", "Business Planning", "Cooperative Finance", "Government Schemes"],
  },
  {
    id: "exam-digital-payments-006",
    name: "Digital Financial Literacy Certification",
    shortName: "DFLC",
    issuer: "NCCT",
    description: "Entry-level certification on digital payments, financial literacy and safe digital transaction practices for cooperative members.",
    eligibility: ["8th pass minimum", "Cooperative or SHG member"],
    eligibilityRules: [
      { field: "education", label: "Minimum Education", operator: "in", value: ["8th Pass", "10th Pass", "12th Pass", "Graduate", "Post-Graduate"], description: "8th standard minimum" },
      ...baseEligibilityRules.slice(1),
    ],
    registrationDeadline: "2026-10-25",
    examDate: "2026-11-15",
    duration: 90,
    durationUnit: "minutes",
    mode: "Online",
    availableSlots: 1000,
    filledSlots: 723,
    fee: 0,
    isFree: true,
    certificateType: "Certificate",
    skillsAssessed: ["Digital Payments", "UPI", "Financial Safety", "DigiLocker"],
    language: ["Hindi", "English", "Marathi", "Gujarati", "Telugu", "Tamil", "Assamese"],
    status: "open",
    passingScore: 50,
    syllabus: ["Digital Payment Basics", "UPI & Mobile Banking", "Financial Safety", "Consumer Rights"],
  },
  {
    id: "exam-supply-chain-007",
    name: "Agri Supply Chain Management Certification",
    shortName: "ASCMC",
    issuer: "NCCT",
    description: "Professional certification for cooperative supply chain and logistics staff managing agricultural commodity movements.",
    eligibility: ["12th pass minimum", "Cooperative operations role"],
    eligibilityRules: [
      { field: "education", label: "Minimum Education", operator: "in", value: ["12th Pass", "Graduate", "Post-Graduate"], description: "12th standard minimum" },
      ...baseEligibilityRules.slice(1),
    ],
    registrationDeadline: "2026-12-10",
    examDate: "2026-12-28",
    duration: 150,
    durationUnit: "minutes",
    mode: "On-Campus",
    availableSlots: 80,
    filledSlots: 42,
    fee: 500,
    isFree: false,
    certificateType: "Certificate",
    skillsAssessed: ["Supply Chain", "Warehouse Management", "Logistics", "APMC Operations"],
    language: ["English", "Hindi", "Telugu"],
    status: "open",
    passingScore: 60,
    syllabus: ["Supply Chain Principles", "Cooperative Procurement", "Warehousing", "Market Integration"],
  },
  {
    id: "exam-cooperative-law-008",
    name: "Cooperative Law Proficiency Test",
    shortName: "CLPT",
    issuer: "NCCT",
    description: "Professional competency test assessing knowledge of Indian cooperative law, MSCS Act and regulatory compliance.",
    eligibility: ["Graduate in Law or Commerce", "Cooperative employment"],
    eligibilityRules: [
      { field: "education", label: "Minimum Education", operator: "in", value: ["Graduate", "Post-Graduate"], description: "Commerce/Law graduate preferred" },
      ...baseEligibilityRules.slice(1),
    ],
    registrationDeadline: "2026-12-20",
    examDate: "2027-01-10",
    duration: 180,
    durationUnit: "minutes",
    mode: "On-Campus",
    availableSlots: 60,
    filledSlots: 28,
    fee: 700,
    isFree: false,
    certificateType: "Certificate",
    skillsAssessed: ["MSCS Act", "State Cooperative Laws", "Audit Law", "Compliance Management"],
    language: ["English", "Hindi"],
    status: "upcoming",
    passingScore: 70,
    syllabus: ["MSCS Act 2002", "State Acts", "Case Law", "Compliance Requirements"],
  },
  {
    id: "exam-milk-quality-009",
    name: "Dairy Milk Quality Analyst Certification",
    shortName: "DMQAC",
    issuer: "NDRI / NCCT",
    description: "Technical certification for dairy laboratory analysts covering advanced milk testing, quality parameters and FSSAI compliance.",
    eligibility: ["12th pass (Science)", "Dairy cooperative lab employment"],
    eligibilityRules: [
      { field: "education", label: "Minimum Education", operator: "in", value: ["12th Pass", "Graduate", "Post-Graduate"], description: "12th Science minimum" },
      ...baseEligibilityRules.slice(1),
    ],
    registrationDeadline: "2026-11-28",
    examDate: "2026-12-15",
    duration: 180,
    durationUnit: "minutes",
    mode: "On-Campus",
    availableSlots: 50,
    filledSlots: 31,
    fee: 800,
    isFree: false,
    certificateType: "Certificate",
    skillsAssessed: ["Milk Testing", "Quality Analysis", "Lab Operations", "FSSAI Standards"],
    language: ["Hindi", "English"],
    status: "open",
    passingScore: 65,
    syllabus: ["Milk Composition Analysis", "Adulteration Detection", "Microbiology Basics", "FSSAI Standards"],
  },
  {
    id: "exam-coop-hr-010",
    name: "Cooperative HR Management Certification",
    shortName: "CHRMC",
    issuer: "NCCT",
    description: "Professional certification for cooperative HR officers covering personnel management, member relations and cooperative industrial relations.",
    eligibility: ["Graduate minimum", "HR or administrative role in cooperative"],
    eligibilityRules: [
      { field: "education", label: "Minimum Education", operator: "in", value: ["Graduate", "Post-Graduate"], description: "Graduate required" },
      ...baseEligibilityRules.slice(1),
    ],
    registrationDeadline: "2027-01-05",
    examDate: "2027-01-25",
    duration: 120,
    durationUnit: "minutes",
    mode: "Online",
    availableSlots: 80,
    filledSlots: 18,
    fee: 400,
    isFree: false,
    certificateType: "Certificate",
    skillsAssessed: ["HR Management", "Labour Law", "Member Relations", "Performance Management"],
    language: ["English", "Hindi"],
    status: "upcoming",
    passingScore: 60,
    syllabus: ["HR Principles", "Labour Legislation", "Cooperative Service Rules", "Conflict Resolution"],
  },
];
