import type { SkillEntry } from "@/lib/types";

export const skillPassport: SkillEntry[] = [
  {
    name: "Cooperative Management",
    category: "Governance",
    level: "Proficient",
    confidence: 92,
    evidence: [
      { type: "Course", title: "Cooperative Management Fundamentals", date: "2026-04-10" },
      { type: "Assessment", title: "Governance & Bylaws Proficiency Test", date: "2026-04-22" },
      { type: "Project", title: "Model Bylaws Draft for Pilot Society", date: "2026-05-02" },
    ],
    verified: true,
    lastUpdated: "2026-05-02",
  },
  {
    name: "Data Analysis",
    category: "Data & Analytics",
    level: "Intermediate",
    confidence: 78,
    evidence: [
      { type: "Assessment", title: "Spreadsheet & Dashboarding Skill Check", date: "2026-06-14" },
      { type: "Project", title: "Member Default-Risk Dashboard", date: "2026-06-28" },
    ],
    verified: true,
    lastUpdated: "2026-06-28",
  },
  {
    name: "Dairy Operations",
    category: "Dairy & Agri-processing",
    level: "Proficient",
    confidence: 88,
    evidence: [
      { type: "Course", title: "Dairy Cooperative Operations", date: "2026-06-18" },
      { type: "Assessment", title: "FAT/SNF Quality Testing Practical", date: "2026-06-20" },
      { type: "Employer Feedback", title: "Field Internship Review - Amul Dairy Union", date: "2026-07-05" },
    ],
    verified: true,
    lastUpdated: "2026-07-05",
  },
  {
    name: "Digital Marketing",
    category: "Marketing & Sales",
    level: "Intermediate",
    confidence: 74,
    evidence: [
      { type: "Course", title: "Digital Marketing for Cooperatives", date: "2026-03-01" },
      { type: "Project", title: "ONDC Storefront Setup for Weaver Society", date: "2026-03-20" },
    ],
    verified: true,
    lastUpdated: "2026-03-20",
  },
  {
    name: "Bookkeeping",
    category: "Finance & Accounts",
    level: "Foundational",
    confidence: 61,
    evidence: [
      { type: "Course", title: "Cooperative Bookkeeping with Tally", date: "2026-08-11" },
    ],
    verified: false,
    lastUpdated: "2026-08-11",
  },
  {
    name: "Leadership & Facilitation",
    category: "Leadership",
    level: "Intermediate",
    confidence: 70,
    evidence: [
      { type: "Course", title: "Leadership for Cooperative Board Members", date: "2026-07-15" },
      { type: "Assessment", title: "Meeting Facilitation Simulation", date: "2026-07-22" },
    ],
    verified: true,
    lastUpdated: "2026-07-22",
  },
  {
    name: "Quality Testing",
    category: "Dairy & Agri-processing",
    level: "Proficient",
    confidence: 82,
    evidence: [
      { type: "Assessment", title: "FAT/SNF Milk Quality Testing Practical", date: "2026-09-19" },
      { type: "Course", title: "Module 4 · Testing and quality control", date: "2026-05-11" },
    ],
    verified: true,
    lastUpdated: "2026-09-19",
  },
  {
    name: "Logistics Planning",
    category: "Dairy & Agri-processing",
    level: "Intermediate",
    confidence: 76,
    evidence: [
      { type: "Project", title: "Capstone · collection-route optimisation model", date: "2026-06-16" },
      { type: "Employer Feedback", title: "Field internship review · Sangli dairy union", date: "2026-06-18" },
    ],
    verified: true,
    lastUpdated: "2026-06-18",
  },
  {
    name: "Tally",
    category: "Finance & Accounts",
    level: "Intermediate",
    confidence: 68,
    evidence: [
      { type: "Course", title: "Cooperative Bookkeeping with Tally", date: "2026-08-11" },
      { type: "Project", title: "Tally migration and reconciliation report", date: "2026-09-08" },
    ],
    verified: true,
    lastUpdated: "2026-09-08",
  },
  {
    name: "Statutory Compliance",
    category: "Governance",
    level: "Intermediate",
    confidence: 71,
    evidence: [
      { type: "Assessment", title: "Practical paper 2 · statutory registers and audit schedule", date: "2026-08-30" },
      { type: "Course", title: "Module 4 · RBI norms, KYC and cooperative audit", date: "2026-07-14" },
    ],
    verified: true,
    lastUpdated: "2026-08-30",
  },
  {
    name: "Governance",
    category: "Governance",
    level: "Proficient",
    confidence: 86,
    evidence: [
      { type: "Course", title: "Leadership for Cooperative Board Members", date: "2026-07-15" },
      { type: "Assessment", title: "Governance & Bylaws Proficiency Test", date: "2026-08-02" },
    ],
    verified: true,
    lastUpdated: "2026-08-02",
  },
  {
    name: "Bylaws Drafting",
    category: "Governance",
    level: "Intermediate",
    confidence: 74,
    evidence: [
      { type: "Project", title: "Capstone · model bylaws for a 400-member PACS", date: "2026-08-01" },
    ],
    verified: true,
    lastUpdated: "2026-08-01",
  },
  {
    name: "Dashboarding",
    category: "Data & Analytics",
    level: "Foundational",
    confidence: 66,
    evidence: [
      { type: "Course", title: "Data Analysis for Cooperative Decision-Making", date: "2026-07-02" },
    ],
    verified: true,
    lastUpdated: "2026-07-02",
  },
  {
    name: "Credit Appraisal",
    category: "Rural Finance",
    level: "Foundational",
    confidence: 63,
    evidence: [
      { type: "Assessment", title: "Crop loan appraisal and sanction note", date: "2026-09-12" },
      { type: "Project", title: "Field placement report · loan tracking at Vaikunth PACS", date: "2026-09-04" },
    ],
    verified: true,
    lastUpdated: "2026-09-12",
  },
  {
    name: "E-commerce",
    category: "Marketing & Sales",
    level: "Foundational",
    confidence: 58,
    evidence: [
      { type: "Course", title: "Digital Marketing for Cooperatives", date: "2026-03-01" },
    ],
    verified: false,
    lastUpdated: "2026-03-01",
  },
];
