"""expand_core_flow_schema

Revision ID: 6f1baa07cc5a
Revises: f7cb59bedd74
Create Date: 2026-09-27 20:42:57.285754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f1baa07cc5a'
down_revision: Union[str, None] = 'f7cb59bedd74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_enrollments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trainee_id', sa.UUID(), nullable=True),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_accessed', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['trainee_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'applications', 'users', ['applicant_id'], ['id'])
    op.create_foreign_key(None, 'applications', 'jobs', ['job_id'], ['id'])
    op.add_column('assessment_results', sa.Column('trainee_id', sa.UUID(), nullable=True))
    op.add_column('assessment_results', sa.Column('score', sa.Integer(), nullable=False))
    op.add_column('assessment_results', sa.Column('passed', sa.Boolean(), nullable=True))
    op.add_column('assessment_results', sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('assessment_results', sa.Column('feedback', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'assessment_results', 'users', ['trainee_id'], ['id'])
    op.add_column('assessments', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('assessments', sa.Column('course_id', sa.UUID(), nullable=True))
    op.add_column('assessments', sa.Column('programme_id', sa.UUID(), nullable=True))
    op.add_column('assessments', sa.Column('skill_name', sa.String(length=255), nullable=True))
    op.add_column('assessments', sa.Column('total_questions', sa.Integer(), nullable=True))
    op.add_column('assessments', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    op.add_column('assessments', sa.Column('passing_score', sa.Integer(), nullable=True))
    op.add_column('assessments', sa.Column('due_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('assessments', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'assessments', 'courses', ['course_id'], ['id'])
    op.create_foreign_key(None, 'assessments', 'programmes', ['programme_id'], ['id'])
    op.alter_column('attendance_sessions', 'qr_token',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_foreign_key(None, 'attendance_sessions', 'programmes', ['programme_id'], ['id'])
    op.add_column('certificates', sa.Column('holder_name', sa.String(length=255), nullable=True))
    op.add_column('certificates', sa.Column('programme_title', sa.String(length=255), nullable=True))
    op.add_column('certificates', sa.Column('issuer', sa.String(length=255), nullable=True))
    op.add_column('certificates', sa.Column('expiry_date', sa.DateTime(), nullable=True))
    op.add_column('certificates', sa.Column('skills_certified', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('certificates', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('courses', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('courses', sa.Column('level', sa.String(length=50), nullable=True))
    op.add_column('courses', sa.Column('duration_hours', sa.Integer(), nullable=True))
    op.add_column('courses', sa.Column('instructor', sa.String(length=255), nullable=True))
    op.add_column('courses', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('courses', sa.Column('enrolled_count', sa.Integer(), nullable=True))
    op.add_column('courses', sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('courses', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('courses', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('courses', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('courses', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_foreign_key(None, 'employer_feedbacks', 'jobs', ['job_id'], ['id'])
    op.create_foreign_key(None, 'employer_feedbacks', 'users', ['trainee_id'], ['id'])
    op.add_column('job_matches', sa.Column('job_id', sa.UUID(), nullable=True))
    op.add_column('job_matches', sa.Column('trainee_id', sa.UUID(), nullable=True))
    op.add_column('job_matches', sa.Column('match_score', sa.Integer(), nullable=True))
    op.add_column('job_matches', sa.Column('matched_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('job_matches', sa.Column('missing_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('job_matches', sa.Column('explanation', sa.Text(), nullable=True))
    op.add_column('job_matches', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'job_matches', 'users', ['trainee_id'], ['id'])
    op.create_foreign_key(None, 'job_matches', 'jobs', ['job_id'], ['id'])
    op.alter_column('jobs', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.add_column('lessons', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('modules', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('skill_gaps', sa.Column('trainee_id', sa.UUID(), nullable=True))
    op.add_column('skill_gaps', sa.Column('target_role', sa.String(length=255), nullable=True))
    op.add_column('skill_gaps', sa.Column('match_score', sa.Integer(), nullable=True))
    op.add_column('skill_gaps', sa.Column('gaps', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('skill_gaps', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'skill_gaps', 'users', ['trainee_id'], ['id'])
    op.add_column('skills', sa.Column('category', sa.String(length=100), nullable=True))
    op.alter_column('skills', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint(None, 'skills', ['name'])
    op.add_column('trainee_skills', sa.Column('confidence', sa.Integer(), nullable=True))
    op.add_column('trainee_skills', sa.Column('verified', sa.Boolean(), nullable=True))
    op.add_column('trainee_skills', sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('trainee_skills', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('trainee_skills', 'trainee_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('trainee_skills', 'skill_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trainee_skills', 'skill_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('trainee_skills', 'trainee_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('trainee_skills', 'updated_at')
    op.drop_column('trainee_skills', 'evidence')
    op.drop_column('trainee_skills', 'verified')
    op.drop_column('trainee_skills', 'confidence')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'skills', type_='unique')
    op.alter_column('skills', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('skills', 'category')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'skill_gaps', type_='foreignkey')
    op.drop_column('skill_gaps', 'created_at')
    op.drop_column('skill_gaps', 'gaps')
    op.drop_column('skill_gaps', 'match_score')
    op.drop_column('skill_gaps', 'target_role')
    op.drop_column('skill_gaps', 'trainee_id')
    op.drop_column('modules', 'title')
    op.drop_column('lessons', 'title')
    op.alter_column('jobs', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'job_matches', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'job_matches', type_='foreignkey')
    op.drop_column('job_matches', 'created_at')
    op.drop_column('job_matches', 'explanation')
    op.drop_column('job_matches', 'missing_skills')
    op.drop_column('job_matches', 'matched_skills')
    op.drop_column('job_matches', 'match_score')
    op.drop_column('job_matches', 'trainee_id')
    op.drop_column('job_matches', 'job_id')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'employer_feedbacks', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'employer_feedbacks', type_='foreignkey')
    op.alter_column('courses', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('courses', 'created_at')
    op.drop_column('courses', 'is_active')
    op.drop_column('courses', 'description')
    op.drop_column('courses', 'skills')
    op.drop_column('courses', 'enrolled_count')
    op.drop_column('courses', 'rating')
    op.drop_column('courses', 'instructor')
    op.drop_column('courses', 'duration_hours')
    op.drop_column('courses', 'level')
    op.drop_column('courses', 'category')
    op.drop_column('certificates', 'created_at')
    op.drop_column('certificates', 'skills_certified')
    op.drop_column('certificates', 'expiry_date')
    op.drop_column('certificates', 'issuer')
    op.drop_column('certificates', 'programme_title')
    op.drop_column('certificates', 'holder_name')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'attendance_sessions', type_='foreignkey')
    op.alter_column('attendance_sessions', 'qr_token',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'assessments', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'assessments', type_='foreignkey')
    op.drop_column('assessments', 'created_at')
    op.drop_column('assessments', 'due_date')
    op.drop_column('assessments', 'passing_score')
    op.drop_column('assessments', 'duration_minutes')
    op.drop_column('assessments', 'total_questions')
    op.drop_column('assessments', 'skill_name')
    op.drop_column('assessments', 'programme_id')
    op.drop_column('assessments', 'course_id')
    op.drop_column('assessments', 'title')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'assessment_results', type_='foreignkey')
    op.drop_column('assessment_results', 'feedback')
    op.drop_column('assessment_results', 'submitted_at')
    op.drop_column('assessment_results', 'passed')
    op.drop_column('assessment_results', 'score')
    op.drop_column('assessment_results', 'trainee_id')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'applications', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_table('course_enrollments')
    # ### end Alembic commands ###
