"""link_programmes_and_courses

Revision ID: d7e48ec4b5f3
Revises: 8ac9d506dd3f
Create Date: 2026-09-27 21:18:09.742610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7e48ec4b5f3'
down_revision: Union[str, None] = '8ac9d506dd3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programme_courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('programme_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('courses', sa.Column('programme_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_courses_programme_id', 'courses', 'programmes', ['programme_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_courses_programme_id', 'courses', type_='foreignkey')
    op.drop_column('courses', 'programme_id')
    op.drop_table('programme_courses')
    # ### end Alembic commands ###
